import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const root=path.resolve(import.meta.dirname,'..');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'data/media-provenance.json'),'utf8'));

test('every media record is explicit about source, rights, relevance and AI status',()=>{
  assert.equal(manifest.total,1095);
  assert.equal(manifest.counts['found-documentary-photograph'],7);
  assert.equal(manifest.counts['found-archival-photograph'],1);
  assert.equal(manifest.counts['official-authorized-video-embed'],6);
  assert.equal(manifest.counts['original-editorial-evidence-graphic'],52);
  assert.equal(manifest.counts['derived-editorial-social-preview'],49);
  assert.equal(manifest.counts['derived-platform-editorial-frame'],980);
  assert.equal(manifest.unresolvedPermissionDependentInstalled,0);
  for(const r of manifest.records){
    for(const key of ['mediaClass','creator','institution','rights','reuseDisposition','relevance','aiStatus','aiEvidence','alt','credit']) assert.ok(r[key],`${r.id} ${key}`);
    assert.doesNotMatch(`${r.title} ${r.relevance} ${r.aiEvidence}`,/generated by ai|midjourney|dall-?e|stable diffusion/i);
  }
});

test('found media has exact online provenance; editorial work never claims to be found',()=>{
  for(const r of manifest.records.filter(r=>r.mediaClass.startsWith('found-'))){
    assert.match(r.canonicalUrl,/^https:\/\/(commons\.wikimedia\.org|www\.loc\.gov)\//);
    assert.match(r.rights,/CC BY|No known restrictions/);
    assert.equal(r.aiStatus,'not-ai-generated');
  }
  for(const r of manifest.records.filter(r=>/editorial/.test(r.mediaClass))){
    assert.match(r.credit,/Original editorial/);
    assert.match(r.relevance,/not documentary|non-quantitative|typography\/evidence graphic/i);
  }
});

test('public provenance desk exposes every found or embedded object and the complete ledger',()=>{
  const html=fs.readFileSync(path.join(root,'rights/media-provenance/index.html'),'utf8');
  assert.match(html,/1,095 media records/);
  assert.match(html,/Zero permission-dependent assets are installed/);
  for(const r of manifest.records.filter(r=>r.mediaClass.startsWith('found-')||r.mediaClass==='official-authorized-video-embed')){
    assert.ok(html.includes(r.canonicalUrl),r.id);
    assert.ok(html.includes(r.title),r.id);
  }
});
