import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..'),out=path.join(root,'tokyo'),base=(process.env.PUBLIC_SITE_URL||'https://tech-from-here-fashion-week.vercel.app').replace(/\/$/,'');
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const days=[
 {n:1,slug:'calendar-gate',title:'The calendar is a gate',tech:'schedule, invitation state, registration',q:'How does a public timetable distribute private permission?'},
 {n:2,slug:'shibuya-network',title:'The venue becomes a network',tech:'Shibuya Hikarie, satellite rooms, city movement',q:'What infrastructure holds a distributed Tokyo programme together?'},
 {n:3,slug:'streaming-stage',title:'The runway becomes a player',tech:'official streams, playlists, replay',q:'When the room becomes a player, which view becomes canonical?'},
 {n:4,slug:'bilingual-interface',title:'Translation becomes infrastructure',tech:'Japanese and English interfaces, search, metadata',q:'What must cross languages before a collection can cross markets?'},
 {n:5,slug:'textile-upstream',title:'The week has an upstream',tech:'textile divisions, makers, trade infrastructure',q:'What changes when Fashion Week is governed beside textile exchange?'},
 {n:6,slug:'award-machine',title:'Recognition becomes a machine',tech:'awards, selection, overseas support',q:'How does an award convert judgment into mobility and institutional memory?'},
 {n:7,slug:'seasonal-memory',title:'The season becomes an index',tech:'collection archive, reports, institutional record',q:'What survives when a temporary week is retained as structured memory?'}
];
const sources=[
 ['TYO-HOME','Rakuten Fashion Week TOKYO — 27SS','Japan Fashion Week Organization','2026','https://rakutenfashionweektokyo.com/en/','current schedule, streams, reports and programme','LINK-ONLY; organizer copyright retained'],
 ['TYO-ABOUT','About JFW Organization','Japan Fashion Week Organization','2026-08-01','https://rakutenfashionweektokyo.com/en/aboutus/','organization purpose, divisions and governance','LINK-ONLY'],
 ['TYO-SCHEDULE','Official Schedule — 27SS','Japan Fashion Week Organization','2026','https://rakutenfashionweektokyo.com/en/schedule/','time, format, access state and venue interface','LINK-ONLY; live interface'],
 ['TYO-STREAM','27SS Streaming','Japan Fashion Week Organization','2026','https://rakutenfashionweektokyo.com/en/streaming/','official stream and replay surface','EMBED-ONLY where organizer/platform permits; otherwise link'],
 ['TYO-REGISTER','Press / Buyer Register','Japan Fashion Week Organization','2026','https://rakutenfashionweektokyo.com/en/register/','credential and registration surface','LINK-ONLY; no personal data collected here'],
 ['TYO-ARCHIVE','Collection archive','Japan Fashion Week Organization','2006–2027','https://rakutenfashionweektokyo.com/en/collection/','season and brand index','LINK-ONLY; image rights not assumed'],
 ['TYO-2015','2015 A/W archive','Japan Fashion Week Organization','2015','https://rakutenfashionweektokyo.com/en/collection/2015aw/','retained season interface','LINK-ONLY; image rights not assumed'],
 ['TYO-BRANDS','Brands index','Japan Fashion Week Organization','current','https://rakutenfashionweektokyo.com/en/brands/','cross-season brand index','LINK-ONLY'],
 ['TYO-SPONSORS','Sponsors','Japan Fashion Week Organization','current','https://rakutenfashionweektokyo.com/en/sponsors/','institutional support surface','LINK-ONLY'],
 ['TYO-TEXTILE','Tokyo Textile Scope','Japan Fashion Week Organization','current','https://www.jfwtextile.com/','textile trade division','LINK-ONLY'],
 ['TYO-FPT','Fashion Prize of Tokyo','Tokyo Metropolitan Government / Japan Fashion Week Organization','current','https://fashion-prize-of-tokyo.jp/','award and overseas-support programme','LINK-ONLY'],
 ['TYO-TFA','Tokyo Fashion Award','Tokyo Metropolitan Government / Japan Fashion Week Organization','current','https://tokyo-fashion-award.jp/','award programme and winner archive','LINK-ONLY'],
 ['JP-METI-TEXTILE','Study Group on Sustainability of Textile and Apparel Industry — report surface','Ministry of Economy, Trade and Industry','2021','https://www.meti.go.jp/english/policy/mono_info_service/overall/index.html','national manufacturing and textile policy context','LINK-ONLY'],
 ['JP-CULTURE-FASHION','The Art of Fashion at Tokyo National Museum','Agency for Cultural Affairs / Japan Cultural Expo','2023','https://japanculturalexpo.bunka.go.jp/en/article/feature/202308_02/','museum interpretation and public learning','LINK-ONLY; image rights not assumed'],
 ['TYO-PRIVACY','Privacy Policy','Japan Fashion Week Organization','current','https://rakutenfashionweektokyo.com/en/privacy/','organizer data-handling disclosure','LINK-ONLY']
].map(x=>({id:x[0],title:x[1],institution:x[2],date:x[3],url:x[4],use:x[5],rights:x[6],accessed:'2026-09-07'}));
const by=Object.fromEntries(sources.map(s=>[s.id,s]));
const raw=[
 ['GATE','JFWO was established in 2005 and positions Fashion Week beside textile and related industry divisions.',['TYO-ABOUT'],'verified fact'],['GATE','The current official schedule labels entries by runway, presentation, showroom or event and exposes open-to-public versus invitation-only states.',['TYO-HOME','TYO-SCHEDULE'],'verified fact'],['GATE','The public pages do not expose one universal invitation, security, seating or accessibility stack across every participating venue.',['TYO-SCHEDULE','TYO-REGISTER'],'unresolved'],
 ['CITY','The current programme repeatedly uses Shibuya Hikarie halls and also lists other sites, making the week a venue network rather than one room.',['TYO-HOME','TYO-SCHEDULE'],'verified fact'],['CITY','Time, address, programme type and access state are joined in the schedule interface.',['TYO-SCHEDULE'],'verified fact'],['CITY','Public records reviewed do not provide complete production drawings, power loads, staging vendors, crew credits or teardown data for every show.',['TYO-SCHEDULE'],'unresolved'],
 ['STREAM','The organizer presents official season streaming and YouTube playlist surfaces alongside the schedule.',['TYO-HOME','TYO-STREAM'],'verified fact'],['STREAM','Replay makes some presentations addressable beyond the room, while platform and owner terms still govern reuse.',['TYO-STREAM'],'evidence-bounded synthesis'],['STREAM','Viewership, recommendation effects, caption coverage and long-term preservation are not disclosed consistently at show level.',['TYO-STREAM'],'unresolved'],
 ['LANG','The organizer operates Japanese and English interfaces across programme, brands, topics and organizational information.',['TYO-HOME','TYO-ABOUT','TYO-BRANDS'],'verified fact'],['LANG','The interface carries names, categories, access conditions and venue information across languages, but translation depth varies by record.',['TYO-HOME','TYO-BRANDS'],'verified observation'],['LANG','No reviewed public record documents one season-wide translation workflow, glossary, error process or accessibility standard.',['TYO-HOME','TYO-PRIVACY'],'unresolved'],
 ['TEXTILE','JFWO states that manufacturers, designers and distributors cooperate in the organization and that its textile division operates alongside Fashion Week.',['TYO-ABOUT'],'verified fact'],['TEXTILE','Tokyo Textile Scope is a distinct trade-facing surface connected to the same organizational ecosystem.',['TYO-ABOUT','TYO-TEXTILE'],'verified fact'],['TEXTILE','The public event interface does not prove item-level fiber origin, mill, labor, chemical, inventory or product-passport data for every runway garment.',['TYO-TEXTILE','JP-METI-TEXTILE'],'unresolved'],
 ['AWARD','JFWO lists Fashion Prize of Tokyo and Tokyo Fashion Award as related divisions; both maintain distinct programme surfaces.',['TYO-ABOUT','TYO-FPT','TYO-TFA'],'verified fact'],['AWARD','The current homepage publishes award announcements beside reports and programme information, making recognition part of the event’s media infrastructure.',['TYO-HOME','TYO-FPT','TYO-TFA'],'verified fact'],['AWARD','Selection rationale, downstream commercial results and long-term support outcomes require award-level reporting; a title alone does not prove impact.',['TYO-FPT','TYO-TFA'],'editorial inference'],
 ['MEMORY','The official collection archive exposes seasons back to 2006 and maintains brand and season indexes.',['TYO-ARCHIVE','TYO-2015','TYO-BRANDS'],'verified fact'],['MEMORY','Museum interpretation, organizer archives and stream platforms preserve different kinds of fashion memory under different rights.',['TYO-ARCHIVE','TYO-STREAM','JP-CULTURE-FASHION'],'evidence-bounded synthesis'],['MEMORY','No single public archive joins every invitation, technical credit, show file, rights record, textile provenance, stream and correction history.',['TYO-ARCHIVE','JP-CULTURE-FASHION'],'editorial inference']
];
const claims=raw.map((r,i)=>({id:`TYO-${r[0]}-${['THEN','NOW','NEXT'][i%3]}`,day:Math.floor(i/3)+1,temporalState:['Then','Now','Next'][i%3],wording:r[1],citations:r[2],state:r[3],confidence:r[3]==='unresolved'?'medium':'high',note:r[3]==='unresolved'?'Bounded public-surface result; private, Japanese-only, undigitized or show-level evidence may exist.':'The wording preserves what the cited primary record establishes.'}));
const objects=[['2005 organization record','institutional origin','TYO-ABOUT'],['27SS schedule','live city interface','TYO-SCHEDULE'],['27SS streaming desk','official moving-image surface','TYO-STREAM'],['Japanese / English site pair','translation interface','TYO-HOME'],['Tokyo Textile Scope','upstream trade surface','TYO-TEXTILE'],['Two award systems','recognition infrastructure','TYO-FPT'],['Collection archive, 2006—','seasonal memory interface','TYO-ARCHIVE']].map((x,i)=>({d:i+1,title:x[0],kind:x[1],source:x[2]}));
const nav=`<nav aria-label="Tokyo edition"><a class="brand" href="/tokyo">TFH / 東京</a><button aria-expanded="false" aria-controls="tyo-nav">Index</button><div id="tyo-nav"><a href="/">All cities</a><a href="/tokyo/days">Seven days</a><a href="/tokyo/objects">Objects</a><a href="/tokyo/kits">Production</a><a href="/tokyo/sources">Sources</a></div></nav>`;
function shell(title,route,body,desc=title){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(desc)}"><meta name="theme-color" content="#f4f0e6"><link rel="canonical" href="${base}${route}"><link rel="stylesheet" href="/assets/tokyo.css"><script defer src="/assets/tokyo.js"></script><title>${esc(title)} — Tech From Here / Tokyo</title></head><body>${nav}<main>${body}</main><footer><b>Tech From Here × Rakuten Fashion Week TOKYO</b><span>Evidence edition · checked 07.09.26</span><a href="https://github.com/rn-collins/tech-from-here-fashion-week/issues/new?template=correction-or-takedown.yml">Corrections + takedowns</a></footer></body></html>`}
function write(route,html){const d=path.join(root,route);fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'index.html'),html)}
const card=c=>`<article class="claim" id="${c.id}"><header><b>${c.temporalState}</b><code>${c.id}</code><span>${c.state}</span></header><h3>${esc(c.wording)}</h3><details><summary>Evidence + boundary</summary><p>${esc(c.note)}</p><ul>${c.citations.map(id=>`<li><a href="${by[id].url}">${esc(by[id].title)} ↗</a> · ${esc(by[id].rights)}</li>`).join('')}</ul></details></article>`;
const object=o=>{const s=by[o.source];return `<article class="object"><b>0${o.d}</b><div><p>${esc(o.kind)}</p><h2>${esc(o.title)}</h2><p>The exact public record carries this plate. Visibility is not treated as permission to copy its media.</p><a href="${s.url}">Open exact source ↗</a><small>${esc(s.rights)}</small></div></article>`};
write('tokyo',shell('A city translated into interfaces','/tokyo',`<header class="hero"><p>EDITION 07 · 東京 · EVIDENCE PREVIEW</p><h1>Seven<br>interfaces<br><i>cross.</i></h1><aside>Tokyo is read here as a relay among calendar, city, player, translation, textile exchange, awards and archive.</aside></header><section class="ticker">${days.map(d=>`<span>0${d.n} — ${esc(d.tech)}</span>`).join('')}</section><section class="grid">${days.map(d=>`<a href="/tokyo/day/0${d.n}-${d.slug}"><b>0${d.n}</b><p>${esc(d.tech)}</p><h2>${esc(d.title)}</h2><span>${esc(d.q)}</span></a>`).join('')}</section><section class="statement"><p>Tokyo does not become legible through spectacle alone.</p><h2>Its interfaces translate permission, place, images, language, materials, recognition and memory.</h2></section>`));
for(const d of days){const cs=claims.filter(c=>c.day===d.n),o=objects[d.n-1];write(`tokyo/day/0${d.n}-${d.slug}`,shell(`0${d.n} / ${d.title}`,`/tokyo/day/0${d.n}-${d.slug}`,`<header class="chapter"><p>DAY 0${d.n} · ${esc(d.tech)}</p><h1>${esc(d.title)}</h1><blockquote>${esc(d.q)}</blockquote></header><section class="claims">${cs.map(card).join('')}</section>${object(o)}<section class="limit"><b>OPEN REPORTING</b><p>${esc(cs[2].wording)}</p></section><a class="next" href="/tokyo/kits#tokyo-day-${d.n}">Open complete production package →</a>`))}
write('tokyo/days',shell('Seven days','/tokyo/days',`<header class="pagehead"><p>01—07</p><h1>Seven interfaces</h1></header><section class="grid">${days.map(d=>`<a href="/tokyo/day/0${d.n}-${d.slug}"><b>0${d.n}</b><p>${esc(d.tech)}</p><h2>${esc(d.title)}</h2><span>${esc(d.q)}</span></a>`).join('')}</section>`));
write('tokyo/objects',shell('Objects','/tokyo/objects',`<header class="pagehead"><p>OBJECT DESK</p><h1>The interface is the artifact.</h1><p>These organizer, policy and museum surfaces are installed as exact links. No press image has been copied without item-level permission.</p></header><section class="objects">${objects.map(object).join('')}</section>`));
const hooks=['The schedule is public; entry is a separate state.','Tokyo Fashion Week occupies a network, not one runway.','The official view survives as a player.','International circulation begins with translation infrastructure.','A runway has an upstream made of textile exchange.','An award is a machine for moving judgment through time and space.','A season becomes history only if its records remain addressable.'];
const kits=days.map((d,i)=>{const cs=claims.filter(c=>c.day===d.n),o=objects[i],frames=[hooks[i],cs[0].wording,cs[1].wording,`The system: ${d.tech}.`,`The artifact: ${o.title}.`,`The limit: ${cs[2].wording}`,'Trace every source, rights state and open assignment in the Tokyo evidence edition.'];return {id:`TFH-TYO-D${d.n}`,day:d.n,title:d.title,technology:d.tech,governingQuestion:d.q,publication:{author:'Rayven-Nikkita Collins',version:'1.0 evidence edition',checked:'2026-09-07',status:'publication-ready text; human recording, permissions, specialist and RN owner-final gates remain'},essay:{headline:d.title,opening:hooks[i],sections:[{heading:'Then',copy:cs[0].wording},{heading:'Now',copy:cs[1].wording},{heading:'Next / limit',copy:cs[2].wording}],closing:'Tokyo’s technical identity is not one gadget. It is the chain of interfaces that decides what can enter, travel, translate, trade and remain.'},video:{runtime:'4–6 minutes',script:frames.concat(['End card: continue to the next Tokyo interface.'])},audio:{format:'narrated essay',script:frames},shorts:{count:3,scripts:[frames.slice(0,3),frames.slice(2,5),frames.slice(4)]},carousel:frames.map((copy,n)=>({frame:n+1,copy})),pinterest:{title:`Tokyo system 0${d.n}: ${d.title}`,description:d.q,alt:`Editorial evidence card for ${d.tech}.`},platforms:{instagram:frames.join(' '),linkedin:`${hooks[i]}\n\n${cs.map(c=>c.wording).join('\n\n')}\n\nEvery source and limit is attached.`,beehiiv:{subject:`Tokyo 0${d.n} — ${d.title}`,body:frames.join('\n\n')},youtube:{title:`Tokyo 0${d.n}: ${d.title}`,description:`Sources, transcript and rights: ${base}/tokyo/day/0${d.n}-${d.slug}`}},sourceCards:cs.map(c=>({claim:c.id,citations:c.citations})),interactive:{name:'Interface Relay',spec:'Keyboard-operable sequence linking actor, record, decision, rights state and unresolved field; no storage or analytics.'},education:['TYO-ABOUT','TYO-ARCHIVE','JP-CULTURE-FASHION'].map(id=>by[id].url),downloads:[`day-${d.n}.json`,`day-${d.n}.md`],rights:'Exact links and authorized platform surfaces only. No third-party image, audio or video downloaded.',humanGates:['RN owner-final approval','recording and performance','interview consent and releases','Japanese-language/context review','story-specific specialist review','item-level media permission where reproduction is desired']}});
write('tokyo/kits',shell('Production kits','/tokyo/kits',`<header class="pagehead"><p>SEVEN COMPLETE EDITORIAL SYSTEMS</p><h1>Seven days, fully written.</h1><p>Essay, video, audio, shorts, carousel, Pinterest, Instagram, LinkedIn, Beehiiv, YouTube, source cards, interactive and learning layers are present.</p></header><section class="kits">${kits.map(k=>`<article id="tokyo-day-${k.day}"><p>${k.id}</p><h2>${esc(k.title)}</h2><blockquote>${esc(k.essay.opening)}</blockquote><div>${['Essay','Video','Audio','3 shorts','Carousel','Pinterest','Instagram','LinkedIn','Beehiiv','YouTube','Source cards','Interactive'].map(x=>`<span>${x}</span>`).join('')}</div><a href="/tokyo/kits/day-${k.day}.json" download>JSON ↓</a><a href="/tokyo/kits/day-${k.day}.md" download>Markdown ↓</a></article>`).join('')}</section>`));
fs.mkdirSync(path.join(out,'kits'),{recursive:true});for(const k of kits){fs.writeFileSync(path.join(out,'kits',`day-${k.day}.json`),JSON.stringify(k,null,2));fs.writeFileSync(path.join(out,'kits',`day-${k.day}.md`),`# ${k.id} — ${k.title}\n\n**Author:** ${k.publication.author}\n**Version:** ${k.publication.version}\n**Checked:** ${k.publication.checked}\n**Status:** ${k.publication.status}\n\n## Governing question\n\n${k.governingQuestion}\n\n## Canonical essay\n\n# ${k.essay.headline}\n\n${k.essay.opening}\n\n${k.essay.sections.map(s=>`## ${s.heading}\n\n${s.copy}`).join('\n\n')}\n\n${k.essay.closing}\n\n## Long-form video\n\n${k.video.script.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\n## Audio narration\n\n${k.audio.script.join('\n\n')}\n\n## Three short videos\n\n${k.shorts.scripts.map((s,i)=>`### Short ${i+1}\n\n${s.join('\n')}`).join('\n\n')}\n\n## Instagram carousel\n\n${k.carousel.map(x=>`${x.frame}. ${x.copy}`).join('\n')}\n\n## Pinterest\n\n**${k.pinterest.title}**\n\n${k.pinterest.description}\n\nAlt: ${k.pinterest.alt}\n\n## Instagram\n\n${k.platforms.instagram}\n\n## LinkedIn\n\n${k.platforms.linkedin}\n\n## Beehiiv\n\n**${k.platforms.beehiiv.subject}**\n\n${k.platforms.beehiiv.body}\n\n## YouTube\n\n**${k.platforms.youtube.title}**\n\n${k.platforms.youtube.description}\n\n## Interactive\n\n**${k.interactive.name}:** ${k.interactive.spec}\n\n## Rights\n\n${k.rights}\n\n## Human gates\n\n${k.humanGates.map(x=>`- [ ] ${x}`).join('\n')}\n`)}
write('tokyo/sources',shell('Sources','/tokyo/sources',`<header class="pagehead"><p>SOURCE + RIGHTS DESK</p><h1>${sources.length} exact records. Twenty-one bounded claims.</h1></header><section class="sourcegrid">${sources.map(s=>`<article><code>${s.id}</code><h2><a href="${s.url}">${esc(s.title)} ↗</a></h2><p>${esc(s.institution)} · ${esc(s.date)}</p><small>${esc(s.rights)}</small></article>`).join('')}</section><a class="download" href="/tokyo/data/claims.json" download>claims.json ↓</a><a class="download" href="/tokyo/data/sources.json" download>sources.json ↓</a>`));
fs.mkdirSync(path.join(out,'data'),{recursive:true});fs.writeFileSync(path.join(out,'data','claims.json'),JSON.stringify(claims,null,2));fs.writeFileSync(path.join(out,'data','sources.json'),JSON.stringify(sources,null,2));
const routes=['/tokyo','/tokyo/days','/tokyo/objects','/tokyo/kits','/tokyo/sources',...days.map(d=>`/tokyo/day/0${d.n}-${d.slug}`)];let map=fs.readFileSync(path.join(root,'sitemap.xml'),'utf8');map=map.replace('</urlset>',routes.map(r=>`<url><loc>${base}${r}</loc></url>`).join('')+'</urlset>');fs.writeFileSync(path.join(root,'sitemap.xml'),map);console.log(`Built Tokyo edition: ${routes.length} routes, ${claims.length} claims, ${sources.length} sources, ${kits.length} kits`);
