import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..'),out=path.join(root,'milan'),base=(process.env.PUBLIC_SITE_URL||'https://tech-from-here-fashion-week.vercel.app').replace(/\/$/,'');
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const days=[
 {n:1,slug:'invitation-trademark',title:'The invitation is also a trademark',tech:'Calendar, accreditation, brand control',q:'Who may enter Milano Fashion Week—and who may claim its name?'},
 {n:2,slug:'city-palazzo',title:'The city becomes a sequence of rooms',tech:'Palazzi, Fashion Hub, distributed venues',q:'How does Milan turn heritage architecture into temporary fashion infrastructure?'},
 {n:3,slug:'craft-machine',title:'The machine carries the hand',tech:'Manufacturing, craft, digital fabrication',q:'Where does Italian craft end and technical production begin?'},
 {n:4,slug:'digital-hub',title:'The front row learned every time zone',tech:'Digital Fashion Hub, livestream, VOD',q:'What did Milan preserve when the runway became a platform?'},
 {n:5,slug:'showroom-order',title:'Eight hundred showrooms become a network',tech:'B2B, B2C, wholesale, market access',q:'How does Milan convert spectacle into an order?'},
 {n:6,slug:'traceability',title:'The label becomes a data surface',tech:'ESPR, Digital Product Passport, traceability',q:'Which claims about a garment will become machine-readable—and who must supply them?'},
 {n:7,slug:'archive-memory',title:'Made in Italy needs a memory system',tech:'Archives, film, image rights, preservation',q:'What survives Milan after the room, stream and order book close?'}
];
const sources=[
 ['MI-CNMI-HOME','Milano Fashion Week: calendar, dates and access notice','Camera Nazionale della Moda Italiana','current','https://www.cameramoda.it/en/','official organizer interface','LINK-ONLY; organizer text quoted sparingly'],
 ['MI-CNMI-DIGITAL','Milano Digital Fashion Week','CNMI','2020-06-29','https://www.cameramoda.it/en/associazione/news/1607/','official platform announcement','LINK-ONLY'],
 ['MI-CNMI-JUNE','Milano Moda Uomo moves to September','CNMI','2020-03-27','https://www.cameramoda.it/en/associazione/news/1598/','official schedule announcement','LINK-ONLY'],
 ['MI-CNMI-HUB','Designers for the Planet open call','CNMI','2024-05-21','https://www.cameramoda.it/en/associazione/news/1672/','official open call','LINK-ONLY'],
 ['MI-CNMI-FIALLO','Felipe Fiallo designer record','CNMI','2026','https://www.cameramoda.it/en/milano-moda-donna/fashion-hub-market/designer/142-felipe-fiallo/','official Fashion Hub record','LINK-ONLY'],
 ['MI-CNMI-YT','CNMI multibrand virtual showroom','CNMI / YouTube','2020','https://www.youtube.com/watch?v=PKMQCwTfcaE','official video','AUTHORIZED EMBED via YouTube privacy-enhanced player'],
 ['MI-CNMI-APP','Camera Moda app','CNMI / Apple App Store','current','https://apps.apple.com/us/app/camera-moda/id534578351','official application listing','LINK-ONLY'],
 ['MI-CNMI-SUSTAIN','CNMI sustainability program','CNMI','current','https://www.cameramoda.it/en/sustainability/','official learning resource','LINK-ONLY'],
 ['MI-CNMI-MANIFESTO','Manifesto for sustainability in Italian fashion','CNMI','2012','https://www.cameramoda.it/media/pdf/manifesto_sostenibilita_en.pdf','official framework PDF','LINK-ONLY'],
 ['MI-CNMI-SHOWROOM','Milano Moda Main virtual showroom archive','CNMI','current archive','https://www.cameramoda.it/en/milano-moda-main/','official market resource','LINK-ONLY'],
 ['MI-EU-ESPR','Regulation (EU) 2024/1781','EUR-Lex','2024-06-28','https://eur-lex.europa.eu/eli/reg/2024/1781/oj','binding EU law','PUBLIC LEGAL RECORD; LINK-ONLY'],
 ['MI-EU-DPP','Ecodesign for Sustainable Products Regulation','European Commission','current','https://environment.ec.europa.eu/topics/circular-economy/ecodesign-sustainable-products-regulation_en','official policy explainer','LINK-ONLY'],
 ['MI-EU-TEXTILE','EU Strategy for Sustainable and Circular Textiles','European Commission','current','https://environment.ec.europa.eu/strategy/textiles-strategy_en','official policy page','LINK-ONLY'],
 ['MI-MIMIT-MADEITALY','Made in Italy framework','Italian Ministry of Enterprises and Made in Italy','current','https://www.mimit.gov.it/en/','government discovery surface','LINK-ONLY; exact fashion-week implementation unresolved'],
 ['MI-EUIPO-MFW','European Union trade mark search','EUIPO','current','https://euipo.europa.eu/eSearch/','official trademark search tool','INTERACTIVE LINK; result must be independently saved before claim'],
 ['MI-ARCHIVI-MODA','Fashion archives portal','Direzione Generale Archivi / Italian Ministry of Culture','current','https://archivi.cultura.gov.it/','government archive discovery','LINK-ONLY; item-level rights vary'],
 ['MI-TRIENNALE','Museo del Design Italiano','Triennale Milano','current','https://triennale.org/eng/museum-of-italian-design','museum learning resource','LINK-ONLY'],
 ['MI-MODATECA','Modateca Deanna archive','Modateca Deanna','current','https://www.modateca.it/','specialist textile archive','LINK-ONLY; access and reuse by permission'],
 ['MI-POLIMI','Fashion in Process Research Lab','Politecnico di Milano','current','https://dipartimentodesign.polimi.it/en/research/research-labs/fashion-in-process','university research resource','LINK-ONLY']
].map(x=>({id:x[0],title:x[1],institution:x[2],date:x[3],url:x[4],type:x[5],rights:x[6]}));
const by=Object.fromEntries(sources.map(s=>[s.id,s]));
const raw=[
 ['ACCESS','CNMI describes itself as coordinating Italian fashion and publishes the official calendar; its live notice states events are invitation-only and that CNMI owns the Milano Fashion Week trademark.',['MI-CNMI-HOME'],'verified fact'],['ACCESS','Accreditation, calendar, app and organizer brand control form one public access layer, but invitations remain issued by individual event hosts.',['MI-CNMI-HOME','MI-CNMI-APP'],'editorial synthesis'],['ACCESS','No public organizer record reviewed establishes the guest-list software, identity checks or security stack for the next edition.',['MI-CNMI-HOME'],'unresolved'],
 ['ROOM','CNMI’s Fashion Hub uses Palazzo Giureconsulti as a meeting and presentation site for selected emerging designers.',['MI-CNMI-HUB'],'verified fact'],['ROOM','The official calendar coordinates shows, presentations and digital events across Milan rather than specifying one permanent runway venue.',['MI-CNMI-HOME'],'verified fact'],['ROOM','Room-level lighting, sound, power, accessibility and supplier specifications remain event-by-event reporting assignments.',['MI-CNMI-HOME'],'unresolved'],
 ['CRAFT','CNMI’s Fashion Hub record for Felipe Fiallo identifies digital fabrication, 3D printing, zero-waste and upcycling as methods within an Italy-based footwear practice.',['MI-CNMI-FIALLO'],'verified fact'],['CRAFT','Milan’s technical story includes both industrial systems and institutions that frame craft, innovation and emerging production for buyers and media.',['MI-CNMI-HUB','MI-CNMI-FIALLO'],'editorial synthesis'],['CRAFT','The reviewed public pages do not disclose the factories, software versions, material recipes or labor conditions behind a specific forthcoming collection.',['MI-CNMI-FIALLO'],'unresolved'],
 ['DIGITAL','CNMI says its 2020 Digital Fashion Hub was designed and developed with Accenture, supported by Microsoft technology, with requirements work by PwC.',['MI-CNMI-DIGITAL'],'verified fact'],['DIGITAL','The 2020 platform ran continuously across time zones and supported scheduled brand storytelling, while CNMI also published a multibrand virtual-showroom video.',['MI-CNMI-DIGITAL','MI-CNMI-YT'],'verified fact'],['DIGITAL','A permanent future supplier stack or successor platform is not inferred from the 2020 announcement.',['MI-CNMI-DIGITAL'],'unresolved'],
 ['ORDER','In March 2020 CNMI said Milan’s 800 showrooms would participate in new B2B and B2C storytelling as menswear moved to September.',['MI-CNMI-JUNE'],'verified fact'],['ORDER','CNMI’s Fashion Showroom surface makes market discovery public, but does not expose private orders, prices, sell-through or customer records.',['MI-CNMI-SHOWROOM'],'verified fact'],['ORDER','Which wholesale, ERP or clienteling system converts any named future show into orders remains private unless a brand or vendor documents it.',['MI-CNMI-SHOWROOM'],'unresolved'],
 ['DPP','The EU Ecodesign for Sustainable Products Regulation entered into force in July 2024 and establishes a framework that includes digital product passports.',['MI-EU-ESPR','MI-EU-DPP'],'verified fact'],['DPP','The Digital Product Passport is a regulatory data architecture, not proof that every Milan runway garment currently carries one.',['MI-EU-ESPR','MI-EU-DPP'],'verified fact'],['DPP','Product-group rules, delegated acts and implementation details must be tracked through official EU records; no CNMI-specific future implementation is asserted here.',['MI-EU-DPP','MI-EU-TEXTILE'],'unresolved'],
 ['MEMORY','Italy’s public archive and museum surfaces, Modateca Deanna and Politecnico di Milano preserve different slices of fashion knowledge: records, objects, textiles and research.',['MI-ARCHIVI-MODA','MI-TRIENNALE','MI-MODATECA','MI-POLIMI'],'verified fact'],['MEMORY','CNMI’s live gallery and video surfaces preserve selected official images and moving-image records, but discovery does not equal permission to reproduce.',['MI-CNMI-HOME','MI-CNMI-YT'],'verified fact'],['MEMORY','No complete public, rights-cleared archive of every Milan show, worker, venue, invitation, technical credit and commercial outcome was located.',['MI-ARCHIVI-MODA','MI-CNMI-HOME'],'editorial inference']
];
const claims=raw.map((r,i)=>({id:`MI-${r[0]}-${['THEN','NOW','NEXT'][i%3]}`,day:Math.floor(i/3)+1,temporalState:['Then','Now','Next'][i%3],wording:r[1],citations:r[2],state:r[3],confidence:r[3]==='unresolved'?'medium':'high',note:r[3]==='unresolved'?'Bounded public-surface result; private or undigitized evidence may exist.':'Read with exact sources at point of claim.'}));
const objects=[
 {d:1,title:'The calendar and the protected name',kind:'live organizer interface',source:'MI-CNMI-HOME'},
 {d:2,title:'Palazzo Giureconsulti Fashion Hub',kind:'official open-call record',source:'MI-CNMI-HUB'},
 {d:3,title:'A digitally fabricated footwear practice',kind:'official designer record',source:'MI-CNMI-FIALLO'},
 {d:4,title:'CNMI multibrand virtual showroom',kind:'official authorized video embed',source:'MI-CNMI-YT',embed:'PKMQCwTfcaE'},
 {d:5,title:'Fashion Showroom',kind:'official market interface',source:'MI-CNMI-SHOWROOM'},
 {d:6,title:'Regulation (EU) 2024/1781',kind:'public legal record and educational tool',source:'MI-EU-ESPR'},
 {d:7,title:'Fashion in Process',kind:'university research resource',source:'MI-POLIMI'}];
const nav=`<nav><a class="brand" href="/milan">TFH / MILANO</a><button aria-expanded="false" aria-controls="mi-nav">Menu</button><div id="mi-nav"><a href="/">London</a><a href="/new-york">New York</a><a href="/milan/days">Seven days</a><a href="/milan/objects">Objects</a><a href="/milan/kits">Production</a><a href="/milan/sources">Sources</a></div></nav>`;
function shell(title,route,body,desc=title){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(desc)}"><meta name="theme-color" content="#245c45"><link rel="canonical" href="${base}${route}"><link rel="stylesheet" href="/assets/milan.css"><script defer src="/assets/milan.js"></script><title>${esc(title)} — Tech From Here / Milano</title></head><body>${nav}<main>${body}</main><footer><b>Tech From Here × Milano Fashion Week</b><span>Evidence edition · 03.09.26</span><a href="https://github.com/rn-collins/tech-from-here-fashion-week/issues/new?template=correction-or-takedown.yml">Corrections + takedowns</a></footer></body></html>`};
function write(route,html){const d=path.join(root,route);fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'index.html'),html)}
const claimCard=c=>`<article class="claim" id="${c.id}"><header><b>${c.temporalState}</b><code>${c.id}</code><span>${c.state} · ${c.confidence}</span></header><h3>${esc(c.wording)}</h3><details><summary>Evidence, limits + rights</summary><p>${esc(c.note)}</p><ul>${c.citations.map(id=>`<li><a href="${by[id].url}">${esc(by[id].title)} ↗</a> — ${esc(by[id].rights)}</li>`).join('')}</ul></details></article>`;
function objectCard(o){const s=by[o.source];return `<figure class="object">${o.embed?`<iframe src="https://www.youtube-nocookie.com/embed/${o.embed}" title="Official CNMI multibrand virtual showroom video" loading="lazy" allowfullscreen></iframe>`:`<div class="objectmark" aria-hidden="true">${String(o.d).padStart(2,'0')}</div>`}<figcaption><span>${esc(o.kind)}</span><h2>${esc(o.title)}</h2><p>This object is shown as evidence, with its permission boundary attached.</p><a href="${s.url}">Open exact source ↗</a><small>${esc(s.rights)}</small></figcaption></figure>`}
write('milan',shell('The system wears its history','/milan',`<header class="mihero"><div><p>EDITION 03 · MILANO · EVIDENCE PREVIEW</p><h1>The system<br><i>wears</i><br>its history.</h1></div><aside>Seven systems where palazzo, platform, workshop, showroom, regulation and archive meet.</aside></header><section class="ribbon">${days.map(d=>`<span>${esc(d.tech)}</span>`).join('')}</section><section class="citygrid">${days.map(d=>`<a href="/milan/day/${String(d.n).padStart(2,'0')}-${d.slug}"><b>0${d.n}</b><h2>${esc(d.title)}</h2><p>${esc(d.q)}</p></a>`).join('')}</section><section class="statement"><p>London was a relay. New York was a clock.</p><h2>Milan is an inheritance made operational: the name, room, hand, screen, order, label and archive.</h2><p>This edition does not treat “Made in Italy” as atmosphere. It asks which technical and institutional systems let the claim travel.</p></section>`));
for(const d of days){const cs=claims.filter(c=>c.day===d.n),o=objects[d.n-1];write(`milan/day/${String(d.n).padStart(2,'0')}-${d.slug}`,shell(`0${d.n} / ${d.title}`,`/milan/day/${String(d.n).padStart(2,'0')}-${d.slug}`,`<header class="chapter"><p>DAY 0${d.n} · ${esc(d.tech)}</p><h1>${esc(d.title)}</h1><blockquote>${esc(d.q)}</blockquote></header><section class="claims">${cs.map(claimCard).join('')}</section>${objectCard(o)}<section class="reporting"><b>OPEN REPORTING</b><p>${esc(cs[2].wording)}</p></section><a class="next" href="/milan/kits#mi-day-${d.n}">Open the complete production package →</a>`))}
write('milan/days',shell('Seven days','/milan/days',`<header class="pagehead"><p>01—07</p><h1>Seven technologies of Milan</h1></header><section class="citygrid">${days.map(d=>`<a href="/milan/day/${String(d.n).padStart(2,'0')}-${d.slug}"><b>0${d.n}</b><h2>${esc(d.title)}</h2><p>${esc(d.q)}</p></a>`).join('')}</section>`));
write('milan/objects',shell('Objects','/milan/objects',`<header class="pagehead"><p>OBJECT DESK</p><h1>Seven public objects. Seven explicit permission boundaries.</h1><p>One official authorized embed and six exact primary interfaces; no downloaded imagery whose reuse status is unclear.</p></header><section class="objects">${objects.map(objectCard).join('')}</section>`));
const hooks=['Before the first look, Milan controls a name and an invitation.','Milan does not have one runway; it has rooms carrying centuries into temporary use.','In Milan, the hand and machine are not opposites—they are a production argument.','In 2020, Milan rebuilt the front row as a platform that never slept.','The show is public attention; the showroom is the order system behind it.','A garment label is becoming an interface to regulated product data.','Made in Italy cannot continue without systems that remember how it was made.'];
const kits=days.map((d,i)=>{const cs=claims.filter(c=>c.day===d.n),o=objects[i];const frames=[hooks[i],cs[0].wording,cs[1].wording,`The system: ${d.tech}.`,`The proof: ${by[cs[0].citations[0]].title}.`,`The limit: ${cs[2].wording}`,'Open the Milan evidence edition: every receipt and permission is attached.'];return {id:`TFH-MI-D${d.n}`,day:d.n,title:d.title,technology:d.tech,governingQuestion:d.q,status:'evidence-backed draft; recording, named interviews and owner-final approval remain open',longform:{headline:d.title,opening:hooks[i],sections:[{heading:'Then',copy:cs[0].wording,claimId:cs[0].id},{heading:'Now',copy:cs[1].wording,claimId:cs[1].id},{heading:'Next—and the limit',copy:cs[2].wording,claimId:cs[2].id}],closing:'Milan’s technology is not futurist decoration. It is the system that moves authority from name to room to object to record.'},vertical:{runtime:'45–60 seconds',spokenScript:frames},carousel:frames.map((copy,n)=>({frame:n+1,copy})),platforms:{instagram:`${hooks[i]} Seven receipts trace ${d.tech.toLowerCase()} through Milan—without inventing a private supplier stack.`,linkedin:`${hooks[i]}\n\n${cs.map(c=>c.wording).join('\n\n')}\n\nFull evidence and rights treatment in the Milan edition.`,newsletter:{subject:`Milano 0${d.n} — ${d.title}`,deck:d.q},youtube:`Day ${d.n} examines ${d.tech.toLowerCase()}. Claim-level sources, rights and open reporting: ${base}/milan/day/${String(d.n).padStart(2,'0')}-${d.slug}`},interactive:`A keyboard-operable evidence fitting room switches among Then, Now and Next; labels state verified, synthesis or unresolved without relying on color.`,selectedObject:{title:o.title,sourceId:o.source,treatment:o.kind},claims:cs.map(c=>c.id),sources:[...new Set(cs.flatMap(c=>c.citations))],rights:'Authorized embed or exact outbound link only; no third-party image copied without item-level reuse clearance.',education:['MI-TRIENNALE','MI-POLIMI','MI-EU-DPP'].map(id=>by[id].url),openReporting:cs[2].wording,humanGates:['RN owner-final approval','recording/performance','named interviews and releases','specialist review if claim scope changes']}});
write('milan/kits',shell('Production kits','/milan/kits',`<header class="pagehead"><p>SEVEN COMPLETE EDITORIAL SYSTEMS</p><h1>Finished drafts, not duplicate commissioning shells.</h1></header><section class="kits">${kits.map(k=>`<article id="mi-day-${k.day}"><p>${k.id}</p><h2>${esc(k.title)}</h2><blockquote>${esc(k.longform.opening)}</blockquote><div>${['Long form','Vertical','Carousel','Instagram','LinkedIn','Newsletter','YouTube','Interactive','Object','Rights ledger'].map(x=>`<span>${x}</span>`).join('')}</div><a href="/milan/kits/day-${k.day}.json" download>JSON ↓</a><a href="/milan/kits/day-${k.day}.md" download>Markdown ↓</a></article>`).join('')}</section>`));
fs.mkdirSync(path.join(out,'kits'),{recursive:true});for(const k of kits){fs.writeFileSync(path.join(out,'kits',`day-${k.day}.json`),JSON.stringify(k,null,2));fs.writeFileSync(path.join(out,'kits',`day-${k.day}.md`),`# ${k.id} — ${k.title}\n\n**Status:** ${k.status}\n\n## Governing question\n\n${k.governingQuestion}\n\n## Finished long-form\n\n# ${k.longform.headline}\n\n${k.longform.opening}\n\n${k.longform.sections.map(s=>`## ${s.heading}\n\n${s.copy}\n\nEvidence: ${s.claimId}`).join('\n\n')}\n\n${k.longform.closing}\n\n## Vertical script\n\n${k.vertical.spokenScript.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\n## Carousel\n\n${k.carousel.map(x=>`${x.frame}. ${x.copy}`).join('\n')}\n\n## Instagram\n\n${k.platforms.instagram}\n\n## LinkedIn\n\n${k.platforms.linkedin}\n\n## Newsletter\n\n**${k.platforms.newsletter.subject}**\n\n${k.platforms.newsletter.deck}\n\n## YouTube\n\n${k.platforms.youtube}\n\n## Interactive\n\n${k.interactive}\n\n## Selected object\n\n${k.selectedObject.title} — ${k.selectedObject.treatment}\n\n## Open reporting\n\n${k.openReporting}\n\n## Rights\n\n${k.rights}\n\n## Human gates\n\n${k.humanGates.map(x=>`- [ ] ${x}`).join('\n')}\n`)}
write('milan/sources',shell('Sources','/milan/sources',`<header class="pagehead"><p>SOURCE + RIGHTS DESK</p><h1>${sources.length} exact records. Twenty-one bounded claims.</h1><p>A citation is not a reuse license. Discovery is not proof of a private system.</p></header><section class="sourcegrid">${sources.map(s=>`<article><code>${s.id}</code><h2><a href="${s.url}">${esc(s.title)} ↗</a></h2><p>${esc(s.institution)} · ${esc(s.date)} · ${esc(s.type)}</p><small>${esc(s.rights)}</small></article>`).join('')}</section><a class="download" href="/milan/data/claims.json" download>claims.json ↓</a><a class="download" href="/milan/data/sources.json" download>sources.json ↓</a>`));
fs.mkdirSync(path.join(out,'data'),{recursive:true});fs.writeFileSync(path.join(out,'data','claims.json'),JSON.stringify(claims,null,2));fs.writeFileSync(path.join(out,'data','sources.json'),JSON.stringify(sources,null,2));
const routes=['/milan','/milan/days','/milan/objects','/milan/kits','/milan/sources',...days.map(d=>`/milan/day/${String(d.n).padStart(2,'0')}-${d.slug}`)];let map=fs.readFileSync(path.join(root,'sitemap.xml'),'utf8');map=map.replace('</urlset>',routes.map(r=>`<url><loc>${base}${r}</loc></url>`).join('')+'</urlset>');fs.writeFileSync(path.join(root,'sitemap.xml'),map);console.log(`Built Milan edition: ${routes.length} routes, ${claims.length} claims, ${kits.length} kits`);
