import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const claims=JSON.parse(fs.readFileSync(path.join(root,'data/claims.json')));
const sources=JSON.parse(fs.readFileSync(path.join(root,'data/sources.json')));
const trail=JSON.parse(fs.readFileSync(path.join(root,'data/search-trail.json')));
const base=(process.env.PUBLIC_SITE_URL||'https://tech-from-here-fashion-week.vercel.app').replace(/\/$/,'');
const repository=(process.env.PUBLIC_REPOSITORY_URL||'https://github.com/rn-collins/tech-from-here-fashion-week').replace(/\/$/,'');
const correctionsUrl=`${repository}/issues/new?template=correction-or-takedown.yml`;
const days=[
 {n:1,slug:'access',title:'The invitation is an interface',tech:'Schedule, accreditation, entry',q:'When visibility is public but presence is permissioned, where does access actually live?'},
 {n:2,slug:'stage',title:'The runway is a machine',tech:'Lighting, staging, temporary architecture',q:'Which technical systems manufacture atmosphere—and who is credited for them?'},
 {n:3,slug:'capture',title:'The camera writes the collection',tech:'Photography, moving image, indexing',q:'Who establishes the canonical view, and under what rights?'},
 {n:4,slug:'circulation',title:'The feed becomes the front row',tech:'Livestream, web, algorithmic distribution',q:'Does distributed viewing redistribute authority?'},
 {n:5,slug:'backstage',title:'Compressed labor',tech:'Casting, look tracking, identity data',q:'Does the tool reduce work, relocate it, or make it extractable?'},
 {n:6,slug:'commerce',title:'From attention to object',tech:'Line sheets, wholesale, product data',q:'Where does the runway meet the order—and who owns the data?'},
 {n:7,slug:'memory',title:'What the week leaves behind',tech:'Archives, measurement, accountability',q:'What survives, who can reuse it, and what never entered the record?'}
];
const srcById=Object.fromEntries(sources.map(s=>[s.id,s]));
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const nav=`<nav aria-label="Primary"><a class="wordmark" href="/">TFH / LDN</a><a class="cityswitch" href="/new-york">NYC edition</a><a class="cityswitch" href="/milan">Milano edition</a><button class="navtoggle" aria-expanded="false" aria-controls="primary-links" aria-label="Open site index">Index</button><div class="navlinks" id="primary-links"><a href="/chronology">Chronology</a><a href="/systems">Systems</a><a href="/objects">Objects</a><a href="/search">Search</a><a href="/kits">Kits</a><a href="/sources">Evidence</a></div></nav>`;
function shell(title,body,desc=title){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#141310"><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${base}${locationFor(title)}"><link rel="stylesheet" href="/assets/style.css"><script defer src="/assets/app.js"></script><title>${esc(title)} — Tech From Here</title></head><body>${nav}<main>${body}</main><footer><span>Tech From Here × London Fashion Week</span><span>Evidence edition · checked 03.09.26</span><a href="/about">Method</a><a href="${correctionsUrl}" rel="noreferrer">Corrections + takedowns</a></footer></body></html>`}
function locationFor(title){
 const fixed={'Signal / Seam':'/','Chronology':'/chronology','Search':'/search','Systems':'/systems','Objects':'/objects','Field notes':'/field-notes','Watch':'/watch','Sources':'/sources','Rights':'/rights','Accessibility':'/accessibility','About':'/about','Kits':'/kits'};
 if(fixed[title])return fixed[title];
 const day=days.find(d=>title.startsWith(`0${d.n} / `));
 if(day)return `/day/${String(day.n).padStart(2,'0')}-${day.slug}`;
 throw new Error(`No canonical route mapped for title: ${title}`);
}
function write(route,html){const dir=path.join(root,route);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html)}
const badge=c=>`<span class="badge ${c.state.replace(/\s/g,'-')}">${c.state}</span><span class="confidence">${c.confidence} confidence</span>`;
function claimCard(c){return `<article class="claim" id="${c.id}" data-search="${esc([c.id,c.wording,c.temporalState,c.state].join(' '))}"><header><span class="time">${c.temporalState}</span><code>${c.id}</code></header><h3>${esc(c.wording)}</h3><div class="claimmeta">${badge(c)}</div><p class="note">${esc(c.note||c.rights)}</p><details><summary>Evidence + rights</summary><p>${esc(c.rights)}</p><ul>${c.citations.map(id=>`<li><a href="${srcById[id].url}" rel="noreferrer">${esc(srcById[id].title)}</a> · ${esc(srcById[id].rights)}</li>`).join('')}</ul></details></article>`}
const mediaObjects=[
 {day:1,label:'Access architecture',title:'September 2020 digital schedule',kind:'linked interface',source:'SRC-LFW-DIGITAL-2020',caption:'The BFC records 50 digital-only, 21 hybrid and seven physical-only activations, making the permissions split explicit.',alt:'Linked documentary record; no third-party image reproduced.'},
 {day:2,label:'Spatial record',title:'LFW February 2018 — 360 VR',kind:'official video embed',source:'SRC-BFC-VIDEO-360',caption:'A navigable official moving-image record of shows, presentations and backstage space; not a substitute for production credits.',alt:'British Fashion Council 360-degree London Fashion Week highlights player.'},
 {day:3,label:'Commissioned image',title:'Everything Is Temporary',kind:'official video embed',source:'SRC-BFC-VIDEO-2021',caption:'The BFC-commissioned June 2021 digital opening makes moving image part of the programme itself.',alt:'British Fashion Council official digital opening film player.'},
 {day:4,label:'Distributed event',title:'LFW Digital Highlights',kind:'official video embed',source:'SRC-BFC-VIDEO-DIGITAL-2020',caption:'Official highlights from the June 2020 digital, gender-neutral edition—the event as a distributed media object.',alt:'British Fashion Council London Fashion Week digital highlights player.'},
 {day:5,label:'Worker-visible record',title:'Designer Fashion Fund — Episode 3',kind:'official video embed',source:'SRC-BFC-VIDEO-BACKSTAGE',caption:'Studios and backstage preparation are visible here; worker data systems remain a separate unresolved question.',alt:'British Fashion Council Designer Fashion Fund backstage episode player.'},
 {day:6,label:'Platform specification',title:'LFW web-development tender, 2021',kind:'linked primary document',source:'SRC-BFC-WEB-ITT-2021',caption:'The tender connects audience journeys, livestreaming, e-commerce, wholesale, digital showrooms and named web technologies.',alt:'Linked procurement document; no PDF page reproduced.'},
 {day:7,label:'Preservation pair',title:'2020 retained page / 2026 live schedule',kind:'linked interface pair',source:'SRC-LFW-SCHEDULE-2026',secondary:'SRC-LFW-DIGITAL-2020',caption:'Two organizer-controlled surfaces show what a live interface retains—and what only survives because an event page remains addressable.',alt:'Two linked documentary web records; no third-party image reproduced.'}
];
function mediaObject(o){const s=srcById[o.source],second=o.secondary?srcById[o.secondary]:null;if(s.embedId)return `<figure class="mediaobject"><div class="player"><iframe src="https://www.youtube-nocookie.com/embed/${s.embedId}" title="${esc(o.alt)}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><figcaption><span>${esc(o.label)} · ${esc(o.kind)}</span><h2>${esc(o.title)}</h2><p>${esc(o.caption)}</p><a href="${s.url}" rel="noreferrer">Open official source ↗</a><small>${esc(s.rights)}</small></figcaption></figure>`;return `<article class="linkedobject"><span>${esc(o.label)} · ${esc(o.kind)}</span><h2>${esc(o.title)}</h2><p>${esc(o.caption)}</p><div><a href="${s.url}" rel="noreferrer">Open primary record ↗</a>${second?`<a href="${second.url}" rel="noreferrer">Open paired record ↗</a>`:''}</div><small>${esc(s.rights)}</small></article>`}
const hero=`<section class="cover"><div class="kicker">Edition 01 · London · Evidence preview</div><h1>Signal<br><i>/</i> Seam</h1><p class="dek">Seven technical systems. Twenty-one claim records. No spectacle without provenance.</p><div class="runway" aria-hidden="true"><span></span><span></span><span></span></div><aside><strong>Documentary interface</strong><p>This gallery shows what public evidence can support—and gives uncertainty the same visual weight as fact.</p></aside></section>`;
const dayGrid=`<section class="daygrid" aria-labelledby="seven"><header><p>01—07</p><h2 id="seven">The temporary city, cut open</h2></header>${days.map(d=>`<a href="/day/${String(d.n).padStart(2,'0')}-${d.slug}"><b>0${d.n}</b><span>${esc(d.tech)}</span><h3>${esc(d.title)}</h3><small>3 claims · editable kit</small></a>`).join('')}</section>`;
write('.',shell('Signal / Seam',hero+dayGrid+`<section class="manifesto"><p>Fashion Week is not merely a sequence of clothes.</p><h2>It is a temporary technical city: invitations determine entry; stages manufacture attention; cameras establish the transferable view; platforms distribute presence; backstage systems compress labor; commerce turns attention into orders; archives decide what survives.</h2><a class="arrow" href="/systems">Trace the system →</a></section>`,'A documentary gallery of seven technologies that organize London Fashion Week.'));
for(const d of days){const cs=claims.filter(c=>c.day===d.n),object=mediaObjects.find(o=>o.day===d.n);write(`day/${String(d.n).padStart(2,'0')}-${d.slug}`,shell(`0${d.n} / ${d.title}`,`<header class="chapter"><p>DAY 0${d.n} · ${esc(d.tech)}</p><h1>${esc(d.title)}</h1><blockquote>${esc(d.q)}</blockquote></header><section class="contactsheet">${cs.map(claimCard).join('')}</section><section class="evidenceplate" aria-label="Selected documentary object">${mediaObject(object)}</section><section class="continuity"><span>Continuity / rupture</span><h2>${esc(cs[0].state==='proposal'?'The missing artifact is part of the story. This page refuses to turn a reporting hypothesis into history.':'The interface changes faster than the distribution of authority. The claim records show exactly where that interpretation rests.')}</h2></section><div class="chapterfoot"><a href="/kits#day-${d.n}">Open editable package kit</a><a href="/sources">Audit the evidence</a></div>`));}
write('chronology',shell('Chronology',`<header class="pagehead"><p>Interactive 01</p><h1>Chronology</h1><p>Filter the edition by evidence state. “Next” includes unresolved absences; it does not mean prediction.</p></header><div class="filters" role="group" aria-label="Filter claims"><button data-filter="all" aria-pressed="true">All 21</button><button data-filter="Then">Then</button><button data-filter="Now">Now</button><button data-filter="Next">Next</button></div><section class="timeline">${claims.map(c=>`<a class="timelineitem" data-state="${c.temporalState}" href="/day/${String(c.day).padStart(2,'0')}-${days[c.day-1].slug}#${c.id}"><time>${c.temporalState}</time><code>${c.id}</code><p>${esc(c.wording)}</p></a>`).join('')}</section>`));
write('search',shell('Search',`<header class="pagehead"><p>Interactive 02</p><h1>Search the record</h1><label for="q">Claim ID, wording, evidence state</label><input id="q" class="searchbox" type="search" placeholder="Try: unresolved, access, product passport"><p id="count" aria-live="polite">21 records</p></header><section class="searchresults">${claims.map(claimCard).join('')}</section>`));
write('systems',shell('Systems',`<header class="pagehead"><p>Interactive 03</p><h1>The week is a relay</h1><p>Follow a look through seven governing functions. Each node resolves to evidence—not an illustrative abstraction.</p></header><section class="systemmap">${days.map((d,i)=>`<a href="/day/${String(d.n).padStart(2,'0')}-${d.slug}"><b>0${d.n}</b><h2>${esc(d.slug)}</h2><p>${esc(d.tech)}</p><span>${i<6?'passes to 0'+(d.n+1):'enters the record'}</span></a>`).join('')}</section><aside class="legend"><b>Owner layer</b><span>organizer · venue · supplier · platform · press · buyer · archive</span><b>Evidence rule</b><span>Each relationship is a reporting question until a claim ID proves it.</span></aside>`));
write('objects',shell('Objects',`<header class="pagehead"><p>Object desk</p><h1>Seven records, seven limits</h1><p>Four official video players and three linked primary records now ground the edition. Nothing has been ripped, restaged, or passed off as open-license imagery.</p></header><section class="objectgallery">${mediaObjects.map(mediaObject).join('')}</section>`));
write('field-notes',shell('Field notes',`<header class="pagehead"><p>Reporting desk</p><h1>Field notes</h1><p>No interviews or on-site observations are represented as complete. These are the positions still needed.</p></header><section class="notes">${['Organizer or platform operator','Runway photographer or broadcast producer','Backstage worker or model advocate','Buyer or brand operations lead','Archivist or preservation technologist','Independent sustainability researcher'].map((x,i)=>`<article><code>INT-${String(i+1).padStart(2,'0')}</code><h2>${x}</h2><p>Status: not yet interviewed · consent/release required before audio, image, or quotation.</p></article>`).join('')}</section>`));
write('watch',shell('Watch',`<header class="pagehead"><p>Future contract</p><h1>Plans, pilots, and honest blanks</h1><p>A future earns this page only with a named actor, date, horizon, dependency, and F1–F4 evidence grade.</p></header><section class="watch"><article><span>F1 contextual regulation</span><h2>EU Ecodesign for Sustainable Products Regulation</h2><p>In force since 18 July 2024; includes a framework for digital product passports. Relevant context, not a BFC plan.</p><a href="${srcById['SRC-EU-ESPR'].url}">Primary source ↗</a></article>${days.filter(d=>d.n!==6).map(d=>`<article class="empty"><span>Day 0${d.n} · unresolved</span><h2>${esc(d.slug)}</h2><p>No record has cleared the publication threshold.</p></article>`).join('')}</section>`));
write('sources',shell('Sources',`<header class="pagehead"><p>Source desk</p><h1>Receipts are the interface</h1><p>${sources.length} source-family records. A source can support a claim without licensing its media.</p></header><section class="sourcegrid">${sources.map(s=>`<article><code>${s.id}</code><h2><a href="${s.url}" rel="noreferrer">${esc(s.title)} ↗</a></h2><p>${esc(s.institution)} · ${esc(s.type)}</p><span>${esc(s.rights)}</span></article>`).join('')}</section><a class="download" href="/data/claims.json" download>Download claims.json</a> <a class="download" href="/data/sources.json" download>Download sources.json</a>`));
write('rights',shell('Rights',`<header class="pagehead"><p>Rights desk</p><h1>Public is not permission</h1><p>This release reproduces no third-party image, audio, or video. Every external record is link-only.</p></header><section class="prose"><h2>Treatments</h2><dl><dt>OA–DOWNLOAD</dt><dd>Item page explicitly marks CC0, Public Domain, or compatible Creative Commons.</dd><dt>EMBED–ONLY</dt><dd>Official player/embed offered under current terms.</dd><dt>LINK–ONLY</dt><dd>Evidence may be cited; media is not reproduced.</dd><dt>REQUEST</dt><dd>Written permission or license required.</dd><dt>COMMENTARY–REVIEW</dt><dd>Limited quotation/capture requires editorial and legal review.</dd><dt>DO NOT USE</dt><dd>Unknown provenance, repost, watermark, conflict, synthetic or AI-generated.</dd></dl><h2>Correction / takedown</h2><p><a href="${correctionsUrl}" rel="noreferrer">Open the public correction or takedown form</a> and identify the route, claim ID or object ID, rights basis, and a safe preferred contact method. Do not include private or sensitive information. A challenged object can be removed without erasing its claim history.</p></section>`));
write('accessibility',shell('Accessibility',`<header class="pagehead"><p>Access desk</p><h1>The evidence must travel</h1></header><section class="prose"><h2>Built in</h2><ul><li>Semantic landmarks and heading order</li><li>Keyboard-operable navigation, filters, search, and disclosure controls</li><li>Visible focus states and non-color status labels</li><li>Responsive layouts at 320px and above</li><li>Reduced-motion behavior; no autoplay</li><li>Claim citations visible without hover</li><li>Downloadable JSON and Markdown</li></ul><h2>Required before media publication</h2><p>Alt text, captions, transcript, audio description where needed, deterministic dimensions, and a link fallback for every embed.</p></section>`));
write('about',shell('About',`<header class="pagehead"><p>Method</p><h1>Beauty has to show its receipts</h1><p>Signal / Seam is an evidence preview, not a completed historical exhibition.</p></header><section class="prose"><h2>Four public states</h2><p><b>Verified fact</b> reports what a source directly establishes. <b>Attributed claim</b> preserves who said it. <b>Editorial inference</b> labels interpretation. <b>Proposal</b> names a reporting or design hypothesis. <b>Unresolved</b> stays visible when the record does not clear the threshold.</p><h2>Research boundary</h2><p>Public-surface research does not establish absence. Paywalled, undigitized, private, unstable, and untranslated records may exist. Search trails record where this edition stopped.</p><h2>No synthetic evidence</h2><p>No AI-generated image, synthetic quotation, invented archival material, unsupported superlative, or speculative future belongs in this system.</p><a class="download" href="/data/search-trail.json" download>Download open search trail</a></section>`));
{
 const rightsPath=path.join(root,'rights','index.html');
 const html=fs.readFileSync(rightsPath,'utf8').replace('This release reproduces no third-party image, audio, or video. Every external record is link-only.','This release adds four official YouTube players under embed-only treatment. It downloads no third-party image, audio, or video; all other records remain link-only.');
 fs.writeFileSync(rightsPath,html);
}
const kitSpecs=[
 {hook:'The URL is public. The room is not.',longform:'Map the official schedule as a layered permission system; open with the verified current surface, then expose the missing origin record.',vertical:'Screen-record the public schedule path, stop at the boundary between information and entry, and end on G-ACCESS-01.',carousel:['A public calendar','A private threshold','What the page proves','What it cannot prove','The missing future record'],interactive:'Access Ledger: compare public listing, accreditation, invitation, venue entry, and retained data without collecting user information.',interviews:['BFC accreditation operator','credentialed press member','accessibility adviser'],objectBrief:'Locate one historic invitation or schedule with item-level rights; leave the plate empty until G-OBJECT-04 closes.',teaching:'Who can know an event exists, who can enter, and what evidence distinguishes those permissions?',callout:'Request dated LFW invitations, schedules, and accreditation instructions with provenance and contributor terms.',openGaps:['G-ACCESS-01','G-OBJECT-04','G-FUTURE-07']},
 {hook:'The runway lasts minutes. Its machinery begins before the room exists.',longform:'Build a production-credit anatomy of one season; do not infer a technical stack from spectacle.',vertical:'Follow one lighting cue from plan to atmosphere; publish only after a named credit clears.',carousel:['Venue shell','Temporary build','Cue stack','Crew and teardown','Supplier evidence still missing'],interactive:'Cue Sheet: a keyboard timeline linking light, sound, scenic change, and claim state; placeholders remain visibly unresolved.',interviews:['show producer','lighting or spatial designer','venue technical manager'],objectBrief:'Commission or license a stage plan, lighting plot, or supplier diagram tied to a named show.',teaching:'When does staging technology alter choreography rather than decorate it?',callout:'Request production credits and non-sensitive diagrams from named London crews.',openGaps:['G-SUPPLIER-06','G-FUTURE-07']},
 {hook:'The collection most people meet is a camera position.',longform:'Contrast the official moving-image record with private runway indexes and explain why capture rights shape the canonical view.',vertical:'Freeze one official frame and enumerate camera, owner, platform, file, and what remains unseen—without ripping footage.',carousel:['The room','The camera line','The official film','The private index','The rights boundary'],interactive:'Canonical View Comparator: user selects attendee, official film, press archive, or search index and sees ownership and access fields.',interviews:['runway photographer','broadcast director','fashion archivist'],objectBrief:'Use an authorized BFC video embed only after video-level rights and layered music/footage review.',teaching:'Who writes the collection when most viewers encounter it through a controlled frame?',callout:'Request camera maps, call sheets, and firsthand accounts without unpublished client material.',openGaps:['G-FUTURE-07']},
 {hook:'A livestream widens reach. It does not automatically redistribute attention.',longform:'Reconstruct the claimed early social/livestream chronology while refusing first-language until G-LIVE-02 closes.',vertical:'Put “reach,” “access,” and “ranking” on three separate cards, then show which one public evidence establishes.',carousel:['Signal leaves room','Platform receives it','Feed ranks it','Archive may lose it','First claim held'],interactive:'Front Row / Feed: compare visible fields and delay across room, official stream, channel page, and commercial archive.',interviews:['early digital producer','remote viewer or critic','platform-distribution researcher'],objectBrief:'Secure an exact archived interface capture with timestamp, surrounding context, and commentary review.',teaching:'What changes when a show is viewable but discoverability remains privately ranked?',callout:'Request dated screenshots or recordings of early LFW digital viewing with original source details.',openGaps:['G-LIVE-02','G-PLATFORM-03','G-FUTURE-07']},
 {hook:'Efficiency for production can become extraction from workers.',longform:'Start with the absence of a verified week-wide platform, then report one named workflow from operator and worker perspectives.',vertical:'Trace one field—name, measurement, image, availability, or location—through the backstage workflow and ask who controls it.',carousel:['Paper hypothesis','Data field','Production use','Worker consequence','No biometric claim'],interactive:'Backstage Data Inventory: a non-collecting tool showing purpose, owner, retention, subject right, and unresolved deployment evidence.',interviews:['casting director','model or Equity representative','privacy and labor researcher'],objectBrief:'Do not reproduce casting cards or worker data without consent; prioritize a permissioned blank workflow schema.',teaching:'Does digitization reduce labor, relocate it, or make a worker newly machine-readable?',callout:'Invite workers to describe systems without submitting personal, client, or confidential data.',openGaps:['G-SUPPLIER-06','G-FUTURE-07']},
 {hook:'A regulation can shape the garment without belonging to Fashion Week.',longform:'Separate historic line-sheet practice, unverified current platform adoption, and the enacted EU product-passport framework.',vertical:'Show the sentence “ESPR is not a BFC plan,” then trace regulation → future delegated rules → product data.',carousel:['Order before interface','Vendor is not adoption','Named season required','EU law as context','Implementation is not complete'],interactive:'Product Data Boundary: inspect identifier, material, actor, provenance, and missing field against the enacted-law context.',interviews:['brand operations lead','wholesale buyer','EU product-data specialist'],objectBrief:'Locate a permissioned historic line sheet or create an original schema diagram; no vendor UI screenshot without review.',teaching:'How do we distinguish an enacted framework, a delegated requirement, a vendor product, and an actual brand deployment?',callout:'Request redacted line sheets and confirmed season-specific showroom workflows.',openGaps:['G-SUPPLIER-06']},
 {hook:'What disappears from the archive becomes harder to argue with.',longform:'Follow schedule, film, interface, and measurement record into four different preservation and reuse regimes.',vertical:'Present the seven empty object bays as an editorial fact: no item enters without relevance plus rights.',carousel:['Event happens','Records split','Rights diverge','Metrics need boundaries','Absence remains visible'],interactive:'Claims Fitting Room: test an environmental statement for boundary, baseline, method, verifier, and season.',interviews:['fashion curator','web archivist','independent sustainability researcher'],objectBrief:'Close G-OBJECT-04 with one edition-relevant open object, or retain the designed void.',teaching:'How does preservation infrastructure decide which technical history remains citable?',callout:'Request ephemera and oral-history leads under explicit ownership, consent, withdrawal, and preservation terms.',openGaps:['G-OBJECT-04','G-MEASURE-05','G-FUTURE-07']}
];
const finishedOutputs=[
 {title:'The invitation is an interface',opening:'London Fashion Week can be publicly legible and privately inaccessible at the same time. The schedule tells you that an event exists; accreditation determines whether a professional category is recognized; an invitation determines whether a particular room opens.',argument:['A public URL distributes information, not entry.','The September 2020 record makes the split unusually visible: digital-only work could be encountered globally while physical shows and appointments remained bounded.','The current system still distinguishes public schedule visibility from professional accreditation and invitation-based access.','The unverified part is the future: no dated BFC-owned replacement for this layered access system cleared our evidence threshold.'],vertical:['The calendar is public.','The room is not.','Accreditation recognizes a category.','An invitation authorizes a person.','Those are four different permissions.','London Fashion Week makes them look like one seamless experience.','The technology of access is the seam.'],cta:'Open the Access Ledger and audit which permission each interface actually grants.'},
 {title:'The runway is a machine',opening:'A runway appears effortless because its machinery has been rehearsed out of sight. Space, power, sound, light, seating, security, timing and teardown are not atmosphere around the show; together, they are the show’s operating system.',argument:['The official 360-degree record preserves spatial experience but cannot supply missing production credits.','The current NEWGEN package verifies a producer, production team, basic lighting, seating, sound and security for supported recipients.','That is a bounded programme fact—not evidence of a single supplier stack across the week.','The honest next step is a credited anatomy of one show, built with its workers rather than inferred from spectacle.'],vertical:['A runway is temporary architecture.','Light tells the eye where to look.','Sound tells the body when to feel.','A producer synchronizes the room.','Security governs its edges.','The spectacle lasts minutes.','The machine begins long before the doors open.'],cta:'Watch the official 360 record, then inspect the missing-credit boundary beside it.'},
 {title:'The camera writes the collection',opening:'Most people never encounter a collection in the room. They meet a camera position: selected, timed, compressed, owned and distributed by somebody else.',argument:['Photography and moving image do not merely preserve a runway; they decide which angle becomes repeatable.','Official films, press archives and private indexes create different canonical views with different rights and access.','The BFC’s retained films prove that moving image can be part of the programme itself.','No generative-image deployment is claimed here: indexing, capture and generation are separate technical acts.'],vertical:['The collection walks once.','The camera makes it repeatable.','The edit decides duration.','The platform decides availability.','The archive decides survival.','So who authored the version you remember?','Not only the designer.'],cta:'Use the Canonical View Comparator to inspect owner, frame, access and reuse.'},
 {title:'The feed becomes the front row',opening:'A livestream can widen viewership without redistributing attention. Access to a signal is not the same as visibility inside a ranked feed.',argument:['In June 2020 the BFC launched a freely accessible digital-only platform for public and trade audiences.','By September 2020 the programme carried films, podcasts, conversations, articles and galleries across digital and hybrid formats.','In 2026, moving content remains an explicit condition of digital schedule participation, and shared viewing can return the stream to a physical room.','No unsupported “first livestream” claim survives this edition; the origin record remains open.'],vertical:['The signal leaves the room.','A platform receives it.','A feed ranks it.','A viewer may find it.','An archive may retain it.','Reach, access and attention are not synonyms.','The front row became a distribution problem.'],cta:'Compare room, stream, feed and archive in Front Row / Feed.'},
 {title:'Compressed labor',opening:'Backstage technology promises coordination under impossible time pressure. The same field that makes a show run—a name, image, measurement, availability or location—can also make a worker newly extractable.',argument:['The 2016 official film makes preparation and teams visible without proving a week-wide software system.','Current NEWGEN support confirms human production infrastructure, not a universal casting-data stack.','Public evidence does not establish biometric or digital-identity deployment at London Fashion Week.','Any future claim must be reported from both the operator and the worker side, with consent, retention and subject rights visible.'],vertical:['One garment.','One model.','Five minutes.','A dozen data fields.','Coordination can reduce friction.','It can also expand surveillance.','Ask who controls the field after the show.'],cta:'Open the Backstage Data Inventory; it collects no personal information.'},
 {title:'From attention to object',opening:'The runway becomes a business when attention meets an order. Between those moments sit line sheets, showrooms, buyer journeys, identifiers, product data and systems whose adoption is often claimed more quickly than it can be proved.',argument:['The BFC’s 2021 web tender explicitly designed retailer and buyer journeys around e-commerce, wholesale, digital showrooms and orders.','A platform requirement is not proof that every proposed function was deployed or adopted by every brand.','The EU Ecodesign for Sustainable Products Regulation is enacted context for digital product passports, not a BFC plan.','The missing historic object remains a London-specific line sheet with item-level reuse permission.'],vertical:['A look becomes attention.','Attention becomes inquiry.','Inquiry becomes an order.','An order becomes production data.','Soon, product data may travel farther.','But a regulation is not a rollout.','And a vendor is not adoption.'],cta:'Use Product Data Boundary to separate law, standard, vendor and deployment.'},
 {title:'What the week leaves behind',opening:'Fashion Week disappears by design. The venue returns to another use; the schedule changes; links decay; platforms reorder. What remains becomes the evidence from which future histories are made.',argument:['Schedules, films, museum records and web archives preserve different fragments under different rules.','A retained event page can be citable while its images remain unavailable for reuse.','Environmental accountability requires a boundary, baseline, method, verifier and season—not an unqualified sustainability label.','No complete future event-level measurement system cleared this edition’s threshold.'],vertical:['The show ends.','The room vanishes.','The schedule changes.','The film survives somewhere else.','The rights split from the memory.','What disappears becomes harder to contest.','An archive is accountability infrastructure.'],cta:'Put a claim through the Claims Fitting Room before repeating it.'}
];
const kitRows=days.map((d,i)=>{const cs=claims.filter(c=>c.day===d.n),spec=kitSpecs[i];return {day:d.n,id:`TFH-LON-D${d.n}`,title:d.title,technology:d.tech,governingQuestion:d.q,claimIds:cs.map(c=>c.id),evidenceState:Object.fromEntries(cs.map(c=>[c.temporalState,{claimId:c.id,state:c.state,confidence:c.confidence}])),editorialHook:spec.hook,longformOutline:spec.longform,verticalScriptBrief:spec.vertical,carouselFrames:spec.carousel,interactiveSpecification:spec.interactive,interviewTargets:spec.interviews,objectAndRightsBrief:spec.objectBrief,teachingPrompt:spec.teaching,communityCallout:spec.callout,openGapIds:spec.openGaps,accessibilityPlan:'Publish transcript/captions for time media; alt text or explicit designed-absence label; keyboard path for the interactive; no status conveyed by color alone.',releaseGates:['Every positive claim resolves to cited support','Every media object has item-level rights disposition','Open gaps remain visible in copy and end cards','Named worker/interview consent recorded before quotation'],mediaPolicy:'OA/licensed/original/authorized embed only; no media cleared in this release',status:'day-specific commissioning package; production remains open'}});
for(const [i,k] of kitRows.entries()){
 const f=finishedOutputs[i];
 k.finishedLongform={headline:f.title,opening:f.opening,sections:f.argument,closing:f.cta};
 k.finishedVertical={duration:'45–60 seconds',spokenScript:f.vertical,finalCard:f.cta};
 k.finishedCarousel=f.vertical.map((line,n)=>({frame:n+1,copy:line,sourceLine:n===f.vertical.length-1?'Claim IDs and source links in gallery.':''}));
 k.platformCopy={instagram:`${f.opening} ${f.cta}`,linkedin:`${f.title}\n\n${f.argument.join('\n\n')}\n\n${f.cta}`,newsletterSubject:`Day ${k.day}/7 — ${f.title}`,youtubeDescription:`Day ${k.day} of Signal / Seam examines ${k.technology.toLowerCase()}. Claims, rights treatments, transcript and sources: ${base}/day/${String(k.day).padStart(2,'0')}-${days[i].slug}`};
}
write('kits',shell('Kits',`<header class="pagehead"><p>Seven finished evidence packages</p><h1>One evidence spine. Seven different editorial jobs.</h1><p>Every kit now includes publishable long-form copy, a complete vertical script, seven carousel frames, platform-specific copy, a selected object, sources, rights treatment and honest open reporting gates.</p></header><section class="kits">${kitRows.map(k=>`<article id="day-${k.day}"><p>PACKAGE ${k.id} · ${esc(k.status)}</p><h2>${esc(k.title)}</h2><blockquote>${esc(k.finishedLongform.opening)}</blockquote><div class="deliverables">${['Finished long form','Complete vertical script','Seven-frame carousel','Instagram copy','LinkedIn copy','YouTube description','Selected object','Evidence + rights'].map(x=>`<span>${x}</span>`).join('')}</div><ol>${k.finishedVertical.spokenScript.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><a href="/kits/day-${k.day}.json" download>Complete JSON ↓</a><a href="/kits/day-${k.day}.md" download>Production Markdown ↓</a></article>`).join('')}</section>`));
for(const k of kitRows){fs.mkdirSync(path.join(root,'kits'),{recursive:true});fs.writeFileSync(path.join(root,'kits',`day-${k.day}.json`),JSON.stringify(k,null,2));fs.writeFileSync(path.join(root,'kits',`day-${k.day}.md`),`# ${k.id} — ${k.title}\n\n**Status:** ${k.status}\n\n## Governing question\n\n${k.governingQuestion}\n\n## Finished long-form copy\n\n### ${k.finishedLongform.headline}\n\n${k.finishedLongform.opening}\n\n${k.finishedLongform.sections.map((x,i)=>`### ${i+1}. ${x}\n\n${k.claimIds[i%k.claimIds.length]} anchors this passage; open the gallery claim card before publication.`).join('\n\n')}\n\n${k.finishedLongform.closing}\n\n## Finished vertical script\n\n**Runtime:** ${k.finishedVertical.duration}\n\n${k.finishedVertical.spokenScript.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\n**Final card:** ${k.finishedVertical.finalCard}\n\n## Finished seven-frame carousel\n\n${k.finishedCarousel.map(x=>`${x.frame}. ${x.copy}${x.sourceLine?` — ${x.sourceLine}`:''}`).join('\n')}\n\n## Platform copy\n\n### Instagram\n\n${k.platformCopy.instagram}\n\n### LinkedIn\n\n${k.platformCopy.linkedin}\n\n### Newsletter subject\n\n${k.platformCopy.newsletterSubject}\n\n### YouTube description\n\n${k.platformCopy.youtubeDescription}\n\n## Evidence fitting\n\n${Object.entries(k.evidenceState).map(([state,x])=>`- **${state}:** ${x.claimId} — ${x.state}, ${x.confidence} confidence`).join('\n')}\n\n## Interactive\n\n${k.interactiveSpecification}\n\n## Interview targets\n\n${k.interviewTargets.map(x=>`- ${x}`).join('\n')}\n\n## Object and rights brief\n\n${k.objectAndRightsBrief}\n\n## Teaching prompt\n\n${k.teachingPrompt}\n\n## Community callout\n\n${k.communityCallout}\n\n## Accessibility\n\n${k.accessibilityPlan}\n\n## Open evidence gaps\n\n${k.openGapIds.map(x=>`- ${x}`).join('\n')}\n\n## Release gates\n\n${k.releaseGates.map(x=>`- [ ] ${x}`).join('\n')}\n\n## Media rule\n\n${k.mediaPolicy}\n`)}
for(const f of ['claims.json','sources.json','search-trail.json']){fs.mkdirSync(path.join(root,'data'),{recursive:true})}
for(const k of kitRows){
 const object=mediaObjects.find(o=>o.day===k.day);
 k.selectedObject={title:object.title,sourceId:object.source,treatment:object.kind,caption:object.caption};
 k.mediaPolicy='OA/licensed/original/authorized embed only; selected documentary object installed with exact source-level treatment';
 k.status='evidence-backed production package; interviews and unresolved future reporting remain open';
 const jsonPath=path.join(root,'kits',`day-${k.day}.json`);
 fs.writeFileSync(jsonPath,JSON.stringify(k,null,2));
 const mdPath=path.join(root,'kits',`day-${k.day}.md`);
 let md=fs.readFileSync(mdPath,'utf8').replace('day-specific commissioning package; production remains open',k.status).replace('OA/licensed/original/authorized embed only; no media cleared in this release',k.mediaPolicy);
 md=md.replace('\n## Object and rights brief',`\n## Selected documentary object\n\n${object.title} — ${object.kind}; ${object.caption}\n\n## Object and rights brief`);
 fs.writeFileSync(mdPath,md);
}
{
 const kitsPath=path.join(root,'kits','index.html');
 const html=fs.readFileSync(kitsPath,'utf8').replaceAll('day-specific commissioning package; production remains open','evidence-backed production package; interviews and unresolved future reporting remain open');
 fs.writeFileSync(kitsPath,html);
}
const routes=['/','/chronology','/search','/systems','/objects','/field-notes','/watch','/sources','/rights','/accessibility','/about','/kits',...days.map(d=>`/day/${String(d.n).padStart(2,'0')}-${d.slug}`)];
fs.writeFileSync(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(r=>`<url><loc>${base}${r}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync(path.join(root,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: '+base+'/sitemap.xml\n');
console.log(`Built ${routes.length} routes, ${claims.length} claims, ${kitRows.length} kits for ${base}`);
await import('./build-new-york.mjs');
await import('./build-milan.mjs');
