import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..'),out=path.join(root,'paris'),base=(process.env.PUBLIC_SITE_URL||'https://tech-from-here-fashion-week.vercel.app').replace(/\/$/,'');
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const days=[
 {n:1,slug:'calendar-code',title:'The calendar is a code',tech:'FHCM calendar, accreditation, designation',q:'How does Paris turn institutional recognition into a technical access system?'},
 {n:2,slug:'monument-stage',title:'The monument becomes a machine',tech:'Distributed venues, permits, temporary production',q:'What must a Paris room become before it can carry a show?'},
 {n:3,slug:'official-image',title:'The image enters the calendar',tech:'Collection pages, image metadata, official film',q:'Who authors the view that survives outside the room?'},
 {n:4,slug:'online-week',title:'Paris rebuilt the week online',tech:'Launchmetrics, digital schedules, video distribution',q:'What changed when the official calendar acquired a digital twin?'},
 {n:5,slug:'showroom-network',title:'The showroom is a second runway',tech:'SPHERE, The New Black, buyer access',q:'How does emerging design move from official visibility toward an order?'},
 {n:6,slug:'product-passport',title:'The garment becomes an address',tech:'ESPR, product passport, textile data',q:'Which facts may have to travel with a product—and which rules do not yet exist?'},
 {n:7,slug:'memory-infrastructure',title:'Paris keeps more than the look',tech:'Galliera, Paris Musées, Gallica, preservation',q:'Which objects, interfaces and technical credits enter public memory?'}
];
const sources=[
 ['PA-FHCM-HOME','Fédération de la Haute Couture et de la Mode','FHCM','current','https://www.fhcm.paris/en','official organizer surface','LINK-ONLY'],
 ['PA-FHCM-HISTORY','Our history','FHCM','current','https://www.fhcm.paris/en/our-history','official institutional history','LINK-ONLY'],
 ['PA-FHCM-CALENDAR','Paris Fashion Week official calendar','FHCM','2026','https://www.fhcm.paris/en/paris-fashion-week/calendar','official live calendar','LINK-ONLY'],
 ['PA-FHCM-ACCREDIT','Accreditation portal','FHCM','current','https://accreditation.fhcm.paris/','official access interface','LINK-ONLY; do not submit data in exhibit'],
 ['PA-FHCM-EVENTS','The events of FHCM','FHCM','current','https://www.fhcm.paris/en/the-events-of-fhcm','official digital-platform history','LINK-ONLY'],
 ['PA-FHCM-PFW','Paris Fashion Week','FHCM','2026','https://www.fhcm.paris/en/paris-fashion-week','official week and SPHERE record','LINK-ONLY'],
 ['PA-FHCM-SPHERE24','SPHERE Paris Fashion Week Showroom 2024','FHCM','2024','https://www.fhcm.paris/fr/node/3536','official showroom record','LINK-ONLY'],
 ['PA-FHCM-PARTNERS','The partners','FHCM','current','https://www.fhcm.paris/en/partners','official partner disclosure','LINK-ONLY'],
 ['PA-FHCM-COLLECTION','Givenchy Menswear FW 2024–2025','FHCM','2024','https://www.fhcm.paris/en/collection/givenchy-menswear-fallwinter-2024-2025','official collection interface','LINK-ONLY; Launchmetrics credit visible'],
 ['PA-FHCM-INTERVIEW','A Conversation with Burc Akyol','FHCM','2023','https://www.fhcm.paris/fr/news/a-conversation-with-burc-akyol','official produced interview','AUTHORIZED PAGE EMBED/LINK; layered rights not cleared for download'],
 ['PA-PARISMUSEES-OPEN','Paris Musées public-domain image search','Paris Musées','current','https://www.parismuseescollections.paris.fr/en/recherche/type/oeuvre/mode-acquisition/don-manuel-214180/image-libre/true/materiaux-technique/toile-armure-213835','official open-image discovery interface','PUBLIC DOMAIN filter; item-level record still required before download'],
 ['PA-GALLIERA-COLLECTIONS','Palais Galliera collections','Paris Musées','current','https://www.parismuseescollections.paris.fr/en/recherche/type/oeuvre/ET/denominations/robe%20compos%C3%A9e-166448','official collection search','LINK-ONLY here; item rights vary'],
 ['PA-BNF-GALLICA','Gallica — the BnF digital library','Bibliothèque nationale de France','current','https://www.bnf.fr/en/gallica-bnf-digital-library','national library resource','LINK-ONLY; item rights vary'],
 ['PA-BNF-RICHELIEU','Richelieu research library','Bibliothèque nationale de France','current','https://www.bnf.fr/en/richelieu','national preservation and access record','LINK-ONLY'],
 ['PA-EU-ESPR','Regulation (EU) 2024/1781','EUR-Lex','2024-06-28','https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX%3A02024R1781-20240628','binding EU legal record','PUBLIC LEGAL RECORD; LINK-ONLY'],
 ['PA-EU-TEXTILES','EU Strategy for Sustainable and Circular Textiles','EUR-Lex','2022-03-30','https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX%3A52022DC0141','official policy record','PUBLIC LEGAL RECORD; LINK-ONLY'],
 ['PA-PARIS-EVENTS','Event organization in Paris','Ville de Paris','current','https://www.paris.fr/pages/organiser-un-evenement-sur-l-espace-public-149','municipal discovery surface','LINK-ONLY; show-specific permits unresolved'],
 ['PA-INPI-SEARCH','Data INPI trademark search','Institut national de la propriété industrielle','current','https://data.inpi.fr/','official public search tool','INTERACTIVE LINK; save exact result before asserting registration'],
 ['PA-FHCM-DATES','Upcoming seasons and previous editions','FHCM','current','https://www.fhcm.paris/en/upcoming-seasons-and-previous-editions','official calendar archive','LINK-ONLY']
].map(x=>({id:x[0],title:x[1],institution:x[2],date:x[3],url:x[4],type:x[5],rights:x[6]}));
const by=Object.fromEntries(sources.map(s=>[s.id,s]));
const raw=[
 ['ACCESS','FHCM coordinates Paris Fashion Week and publishes the official calendar; its history traces the federation to the Chambre Syndicale founded in 1868.',['PA-FHCM-HOME','PA-FHCM-HISTORY'],'verified fact'],['ACCESS','The public calendar, accreditation portal and institutional designations are related but distinct permissions: visibility is not admission.',['PA-FHCM-CALENDAR','PA-FHCM-ACCREDIT','PA-FHCM-HISTORY'],'editorial synthesis'],['ACCESS','No public source reviewed establishes the guest-list software, identity checks or security stack for every forthcoming house presentation.',['PA-FHCM-ACCREDIT'],'unresolved'],
 ['ROOM','Paris Fashion Week is distributed across house-selected locations; the FHCM calendar specifies physical and digital formats rather than one permanent runway.',['PA-FHCM-CALENDAR','PA-FHCM-PFW'],'verified fact'],['ROOM','Municipal event rules form one public layer, but they do not disclose a named show’s lighting, power, scenic, accessibility or teardown plan.',['PA-PARIS-EVENTS','PA-FHCM-CALENDAR'],'verified fact'],['ROOM','Venue contracts, permits, suppliers and technical drawings remain show-by-show reporting assignments unless a house, venue or authority publishes them.',['PA-PARIS-EVENTS'],'unresolved'],
 ['IMAGE','FHCM collection pages bind houses and seasons to official digital records, with visible platform or production credits on some pages.',['PA-FHCM-COLLECTION'],'verified fact'],['IMAGE','An official page can preserve film, lookbook and credit context while leaving underlying image, music and performer rights layered and separate.',['PA-FHCM-COLLECTION','PA-FHCM-INTERVIEW'],'editorial synthesis'],['IMAGE','The reviewed public pages do not disclose a universal camera plan, file-delivery specification or archival master standard for all future shows.',['PA-FHCM-COLLECTION'],'unresolved'],
 ['DIGITAL','FHCM states that Paris Fashion Week Online launched in 2020 with Launchmetrics and support from LE DEFI; official calendars now have physical and digital dimensions.',['PA-FHCM-EVENTS'],'verified fact'],['DIGITAL','The digital platform expanded official collection visibility, but a public stream does not establish open admission, neutral ranking or permanent preservation.',['PA-FHCM-EVENTS','PA-FHCM-CALENDAR'],'editorial synthesis'],['DIGITAL','No permanent future supplier stack is inferred from the 2020 partnership or today’s public pages.',['PA-FHCM-EVENTS','PA-FHCM-PARTNERS'],'unresolved'],
 ['ORDER','FHCM says it has operated SPHERE since January 2020 to support selected emerging brands.',['PA-FHCM-PFW','PA-FHCM-SPHERE24'],'verified fact'],['ORDER','For the 2026 womenswear session, FHCM identifies Palais de Tokyo, an invitation-only digital version and The New Black as its technology provider.',['PA-FHCM-PFW'],'verified fact'],['ORDER','The public showroom page does not reveal private buyer accounts, prices, order volumes, sell-through or participating brands’ downstream systems.',['PA-FHCM-PFW'],'unresolved'],
 ['DPP','Regulation (EU) 2024/1781 establishes an ecodesign framework that includes digital product passports and applies through later product-specific requirements.',['PA-EU-ESPR'],'verified fact'],['DPP','The EU textile strategy anticipates product-passport information for textiles; neither record proves every Paris runway look currently carries a passport.',['PA-EU-TEXTILES','PA-EU-ESPR'],'verified fact'],['DPP','Textile-specific delegated rules, data fields and dates must be tracked through official EU records; no FHCM implementation is asserted.',['PA-EU-ESPR','PA-EU-TEXTILES'],'unresolved'],
 ['MEMORY','Palais Galliera, Paris Musées and Gallica expose different public memory systems: museum objects, open-image filters and digitized national collections.',['PA-GALLIERA-COLLECTIONS','PA-PARISMUSEES-OPEN','PA-BNF-GALLICA'],'verified fact'],['MEMORY','Discovery access and reuse permission are separate: Paris Musées marks some public-domain reproductions, while collection and library records require item-level checking.',['PA-PARISMUSEES-OPEN','PA-GALLIERA-COLLECTIONS','PA-BNF-GALLICA'],'verified fact'],['MEMORY','No complete public archive was located that preserves every Paris show’s invitations, worker credits, venue plans, source files, rights and commercial outcomes.',['PA-FHCM-DATES','PA-BNF-RICHELIEU'],'editorial inference']
];
const claims=raw.map((r,i)=>({id:`PA-${r[0]}-${['THEN','NOW','NEXT'][i%3]}`,day:Math.floor(i/3)+1,temporalState:['Then','Now','Next'][i%3],wording:r[1],citations:r[2],state:r[3],confidence:r[3]==='unresolved'?'medium':'high',note:r[3]==='unresolved'?'Bounded public-surface result; private, paywalled or undigitized evidence may exist.':'Exact primary records are attached at point of claim.'}));
const objects=[
 {d:1,title:'Official calendar + accreditation threshold',kind:'paired organizer interfaces',source:'PA-FHCM-CALENDAR'},
 {d:2,title:'Paris public-event permission surface',kind:'municipal reporting interface',source:'PA-PARIS-EVENTS'},
 {d:3,title:'A season made addressable',kind:'official collection interface',source:'PA-FHCM-COLLECTION'},
 {d:4,title:'Paris Fashion Week Online',kind:'official platform history',source:'PA-FHCM-EVENTS'},
 {d:5,title:'SPHERE at Palais de Tokyo',kind:'official showroom interface',source:'PA-FHCM-PFW'},
 {d:6,title:'Regulation (EU) 2024/1781',kind:'public legal record',source:'PA-EU-ESPR'},
 {d:7,title:'Public-domain fashion image finder',kind:'rights-filtered museum interactive',source:'PA-PARISMUSEES-OPEN'}
];
const nav=`<nav><a class="brand" href="/paris">TFH / PARIS</a><button aria-expanded="false" aria-controls="pa-nav">Menu</button><div id="pa-nav"><a href="/">London</a><a href="/new-york">New York</a><a href="/milan">Milan</a><a href="/shanghai">上海</a><a href="/paris/days">Seven days</a><a href="/paris/objects">Objects</a><a href="/paris/kits">Production</a><a href="/paris/sources">Sources</a></div></nav>`;
function shell(title,route,body,desc=title){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(desc)}"><meta name="theme-color" content="#111111"><link rel="canonical" href="${base}${route}"><link rel="stylesheet" href="/assets/paris.css"><script defer src="/assets/paris.js"></script><title>${esc(title)} — Tech From Here / Paris</title></head><body>${nav}<main>${body}</main><footer><b>Tech From Here × Paris Fashion Week</b><span>Evidence edition · 03.09.26</span><a href="https://github.com/rn-collins/tech-from-here-fashion-week/issues/new?template=correction-or-takedown.yml">Corrections + takedowns</a></footer></body></html>`}
function write(route,html){const d=path.join(root,route);fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'index.html'),html)}
const claimCard=c=>`<article class="claim" id="${c.id}"><header><b>${c.temporalState}</b><code>${c.id}</code><span>${c.state} · ${c.confidence}</span></header><h3>${esc(c.wording)}</h3><details><summary>Evidence, limits + rights</summary><p>${esc(c.note)}</p><ul>${c.citations.map(id=>`<li><a href="${by[id].url}">${esc(by[id].title)} ↗</a> — ${esc(by[id].rights)}</li>`).join('')}</ul></details></article>`;
function objectCard(o){const s=by[o.source];return `<figure class="object"><div class="folio" aria-hidden="true">${String(o.d).padStart(2,'0')}</div><figcaption><span>${esc(o.kind)}</span><h2>${esc(o.title)}</h2><p>The object is presented as an exact public record; its permission boundary travels with it.</p><a href="${s.url}">Open exact source ↗</a><small>${esc(s.rights)}</small></figcaption></figure>`}
write('paris',shell('The calendar becomes a city','/paris',`<header class="hero"><p>EDITION 04 · PARIS · EVIDENCE PREVIEW</p><h1>The calendar<br>becomes<br><i>a city.</i></h1><aside>Seven systems between designation and memory. Every aperture has an owner; every object keeps its rights.</aside></header><section class="rail">${days.map(d=>`<span>0${d.n} ${esc(d.tech)}</span>`).join('')}</section><section class="citygrid">${days.map(d=>`<a href="/paris/day/${String(d.n).padStart(2,'0')}-${d.slug}"><b>0${d.n}</b><h2>${esc(d.title)}</h2><p>${esc(d.q)}</p></a>`).join('')}</section><section class="statement"><p>London relays. New York clocks. Milan operationalizes inheritance.</p><h2>Paris codes legitimacy—then distributes it through rooms, images, platforms, orders, product data and archives.</h2></section>`));
for(const d of days){const cs=claims.filter(c=>c.day===d.n),o=objects[d.n-1];write(`paris/day/${String(d.n).padStart(2,'0')}-${d.slug}`,shell(`0${d.n} / ${d.title}`,`/paris/day/${String(d.n).padStart(2,'0')}-${d.slug}`,`<header class="chapter"><p>DAY 0${d.n} · ${esc(d.tech)}</p><h1>${esc(d.title)}</h1><blockquote>${esc(d.q)}</blockquote></header><section class="claims">${cs.map(claimCard).join('')}</section>${objectCard(o)}<section class="reporting"><b>OPEN REPORTING</b><p>${esc(cs[2].wording)}</p></section><a class="next" href="/paris/kits#pa-day-${d.n}">Open the complete production package →</a>`))}
write('paris/days',shell('Seven days','/paris/days',`<header class="pagehead"><p>01—07</p><h1>Seven technical apertures through Paris</h1></header><section class="citygrid">${days.map(d=>`<a href="/paris/day/${String(d.n).padStart(2,'0')}-${d.slug}"><b>0${d.n}</b><h2>${esc(d.title)}</h2><p>${esc(d.q)}</p></a>`).join('')}</section>`));
write('paris/objects',shell('Objects','/paris/objects',`<header class="pagehead"><p>OBJECT DESK</p><h1>Seven records. No decorative evidence.</h1><p>Each exact public interface proves, locates or limits a claim. No image has been copied merely because it was findable.</p></header><section class="objects">${objects.map(objectCard).join('')}</section>`));
const hooks=['Before Paris shows a garment, it codes who belongs on the calendar.','The Paris runway is not a venue. It is a temporary conversion of the city.','For most viewers, Paris Fashion Week is a sequence authored by an image system.','In 2020, the official calendar acquired a digital twin.','The runway produces attention. SPHERE tries to route some of it toward a market.','The garment is becoming an address for regulated product information.','Paris remembers fashion through incompatible systems: museum, library, platform and house.'];
const kits=days.map((d,i)=>{const cs=claims.filter(c=>c.day===d.n),o=objects[i],frames=[hooks[i],cs[0].wording,cs[1].wording,`The system: ${d.tech}.`,`The object: ${o.title}.`,`The honest limit: ${cs[2].wording}`,'Enter the Paris evidence edition; the receipts and permissions are attached.'];return {id:`TFH-PA-D${d.n}`,day:d.n,title:d.title,technology:d.tech,governingQuestion:d.q,status:'evidence-backed production draft; recording, interviews and owner-final approval remain open',longform:{headline:d.title,opening:hooks[i],sections:[{heading:'Then',copy:cs[0].wording,claimId:cs[0].id},{heading:'Now',copy:cs[1].wording,claimId:cs[1].id},{heading:'Next—and the limit',copy:cs[2].wording,claimId:cs[2].id}],closing:'Paris Fashion Week is not one technology. It is a chain of permissions that turns recognition into circulation and circulation into memory.'},vertical:{runtime:'45–60 seconds',spokenScript:frames},carousel:frames.map((copy,n)=>({frame:n+1,copy})),platforms:{instagram:`${hooks[i]} Seven exact records trace ${d.tech.toLowerCase()} without inventing a house’s private stack.`,linkedin:`${hooks[i]}\n\n${cs.map(c=>c.wording).join('\n\n')}\n\nThe Paris edition attaches every source, rights boundary and unresolved assignment.`,newsletter:{subject:`Paris 0${d.n} — ${d.title}`,deck:d.q},youtube:`Day ${d.n} examines ${d.tech.toLowerCase()}. Claims, sources, rights and reporting limits: ${base}/paris/day/${String(d.n).padStart(2,'0')}-${d.slug}`},interactive:`A keyboard-operable aperture map reveals Then, Now and Next claim states, sources and permission boundaries without relying on color.`,selectedObject:{title:o.title,sourceId:o.source,treatment:o.kind},claims:cs.map(c=>c.id),sources:[...new Set(cs.flatMap(c=>c.citations))],rights:'Exact outbound records only in this release; no third-party image, audio or video downloaded without item-level clearance.',education:['PA-BNF-GALLICA','PA-GALLIERA-COLLECTIONS','PA-EU-ESPR'].map(id=>by[id].url),openReporting:cs[2].wording,humanGates:['RN owner-final approval','recording/performance','named interviews and releases','specialist review if claim scope changes']}});
write('paris/kits',shell('Production kits','/paris/kits',`<header class="pagehead"><p>SEVEN COMPLETE EDITORIAL SYSTEMS</p><h1>Finished drafts. Distinct stories. Visible gates.</h1></header><section class="kits">${kits.map(k=>`<article id="pa-day-${k.day}"><p>${k.id}</p><h2>${esc(k.title)}</h2><blockquote>${esc(k.longform.opening)}</blockquote><div>${['Long form','Vertical','Carousel','Instagram','LinkedIn','Newsletter','YouTube','Interactive','Object','Rights'].map(x=>`<span>${x}</span>`).join('')}</div><a href="/paris/kits/day-${k.day}.json" download>JSON ↓</a><a href="/paris/kits/day-${k.day}.md" download>Markdown ↓</a></article>`).join('')}</section>`));
fs.mkdirSync(path.join(out,'kits'),{recursive:true});for(const k of kits){fs.writeFileSync(path.join(out,'kits',`day-${k.day}.json`),JSON.stringify(k,null,2));fs.writeFileSync(path.join(out,'kits',`day-${k.day}.md`),`# ${k.id} — ${k.title}\n\n**Status:** ${k.status}\n\n## Governing question\n\n${k.governingQuestion}\n\n## Finished long-form\n\n# ${k.longform.headline}\n\n${k.longform.opening}\n\n${k.longform.sections.map(s=>`## ${s.heading}\n\n${s.copy}\n\nEvidence: ${s.claimId}`).join('\n\n')}\n\n${k.longform.closing}\n\n## Vertical script\n\n${k.vertical.spokenScript.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\n## Carousel\n\n${k.carousel.map(x=>`${x.frame}. ${x.copy}`).join('\n')}\n\n## Instagram\n\n${k.platforms.instagram}\n\n## LinkedIn\n\n${k.platforms.linkedin}\n\n## Newsletter\n\n**${k.platforms.newsletter.subject}**\n\n${k.platforms.newsletter.deck}\n\n## YouTube\n\n${k.platforms.youtube}\n\n## Interactive\n\n${k.interactive}\n\n## Selected object\n\n${k.selectedObject.title} — ${k.selectedObject.treatment}\n\n## Open reporting\n\n${k.openReporting}\n\n## Rights\n\n${k.rights}\n\n## Human gates\n\n${k.humanGates.map(x=>`- [ ] ${x}`).join('\n')}\n`)}
write('paris/sources',shell('Sources','/paris/sources',`<header class="pagehead"><p>SOURCE + RIGHTS DESK</p><h1>${sources.length} exact records. Twenty-one bounded claims.</h1><p>A public page is evidence, not automatic permission to reproduce its media.</p></header><section class="sourcegrid">${sources.map(s=>`<article><code>${s.id}</code><h2><a href="${s.url}">${esc(s.title)} ↗</a></h2><p>${esc(s.institution)} · ${esc(s.date)} · ${esc(s.type)}</p><small>${esc(s.rights)}</small></article>`).join('')}</section><a class="download" href="/paris/data/claims.json" download>claims.json ↓</a><a class="download" href="/paris/data/sources.json" download>sources.json ↓</a>`));
fs.mkdirSync(path.join(out,'data'),{recursive:true});fs.writeFileSync(path.join(out,'data','claims.json'),JSON.stringify(claims,null,2));fs.writeFileSync(path.join(out,'data','sources.json'),JSON.stringify(sources,null,2));
const routes=['/paris','/paris/days','/paris/objects','/paris/kits','/paris/sources',...days.map(d=>`/paris/day/${String(d.n).padStart(2,'0')}-${d.slug}`)];let map=fs.readFileSync(path.join(root,'sitemap.xml'),'utf8');map=map.replace('</urlset>',routes.map(r=>`<url><loc>${base}${r}</loc></url>`).join('')+'</urlset>');fs.writeFileSync(path.join(root,'sitemap.xml'),map);console.log(`Built Paris edition: ${routes.length} routes, ${claims.length} claims, ${kits.length} kits`);
